const fundamentals = {
  name: "Fundamentals",
  icon: "◆",
  color: "#E8553A",
  concepts: [
    { id: 1, name: "Scalability", desc: `Scalability is a system's ability to handle increased load — more users, more data, more requests — without degrading in performance or requiring a complete redesign. It is not about handling today's load well; it's about being architected so that capacity can grow incrementally as demand grows. Every successful system eventually confronts a scalability ceiling, and whether that ceiling is hit gracefully or catastrophically depends on decisions made early in the design.

**How it works:**
- **Vertical scaling (scaling up):** Add more resources (CPU, RAM, disk) to the existing server. Simple — no code changes required. Has hard limits (you can't add infinite RAM to one machine) and creates a single point of failure. Works well for databases in early stages.
- **Horizontal scaling (scaling out):** Add more machines to distribute the load. Requires a load balancer to distribute traffic. Applications must be stateless (or share state via external cache/DB) to scale horizontally. The dominant model for web-scale systems.
- **Stateless vs stateful scaling:** Stateless services (each request carries all needed context) scale trivially — spin up any number of instances. Stateful services (in-memory session, local files) require sticky sessions, distributed session stores, or redesign before they can scale horizontally.
- **Data layer scaling:** Application servers scale easily; databases are the hard part. Read replicas for read-heavy workloads, sharding for write-heavy workloads, and caching (Redis/Memcached) to reduce DB load are the standard progression.
- **Auto-scaling:** Cloud platforms (AWS Auto Scaling, Kubernetes HPA) monitor load metrics and automatically add/remove instances. Requires health checks, graceful startup/shutdown, and idempotent operations.

**Real-world example:** Instagram's backend in 2012 served 30 million users with 3 engineers and a handful of servers — by keeping the application stateless (Django), scaling reads with PostgreSQL replicas, and aggressively caching with Redis. When traffic spiked, they scaled by adding more web workers horizontally. By the time they reached 1 billion users, the architecture had evolved to hundreds of microservices and thousands of servers, but the core principle — stateless application tier, scaled-out data tier — remained the same.

**Key takeaway:** Design your application tier to be stateless from day one — it costs almost nothing upfront and makes horizontal scaling trivial later. Don't over-engineer early, but don't paint yourself into a stateful corner. The standard progression is: vertical scaling first (quick wins), then read replicas, then caching, then sharding — each step buys time for the next.` },
    { id: 2, name: "Availability", desc: `Availability is the percentage of time a system is operational and serving requests correctly. It is the most customer-visible reliability metric — when a system is down, users know immediately. Availability is typically expressed in "nines": 99% (two nines), 99.9% (three nines), 99.99% (four nines). The gap between three nines and four nines sounds small (0.09%) but represents the difference between ~8.7 hours and ~52 minutes of acceptable downtime per year — and the engineering cost to achieve four nines is dramatically higher than three.

**How it works:**
- **Availability math:** Availability = Uptime / (Uptime + Downtime). For a system with two independent components in series (both must work), availability multiplies: 99.9% × 99.9% = 99.8%. For components in parallel (either can work), availability improves: 1 - (0.001 × 0.001) = 99.9999%. This is why redundancy is the primary tool for improving availability.
- **Nines and their meaning:** 99% (two nines) = 87.6 hours downtime/year. 99.9% = 8.76 hours. 99.99% = 52 minutes. 99.999% = 5.26 minutes. Moving from 99.9% to 99.999% requires eliminating planned maintenance windows, zero-downtime deployments, multi-region failover, and extensive chaos engineering.
- **Achieving high availability:** Eliminate single points of failure (redundant everything), deploy across multiple availability zones, use health checks and automatic failover, implement graceful degradation (serve degraded functionality rather than returning errors), and practice chaos engineering to find failure modes before they cause outages.
- **Planned vs unplanned downtime:** Most teams focus on unplanned outages, but planned maintenance (deployments, migrations) often causes more downtime. Zero-downtime deployments (blue/green, canary, rolling) are essential for high availability targets.
- **Geographic redundancy:** Multi-region architectures tolerate entire cloud region failures. Active-active (traffic split across regions) vs active-passive (failover to standby region). Comes with significant complexity (distributed transactions, data replication lag, DNS TTL considerations).

**Real-world example:** AWS S3 targets 99.99% availability (four nines) for its standard storage tier. Achieving this requires data distributed across at least three availability zones, automatic failover when a zone goes down, and operations that remain available even during zone outages. AWS publicly maintains a Service Health Dashboard and issues credits when SLAs are violated — the financial commitment creates internal pressure to hit the target.

**Key takeaway:** Don't target four nines unless your business genuinely requires it — the last nines are exponentially expensive. Start with 99.9%, which most applications can achieve with basic redundancy and load balancing. Calculate the actual business cost of downtime (revenue loss, SLA penalties, support cost) and set your availability target accordingly. Architecture decisions flow from the target, not the other way around.` },
    { id: 3, name: "Reliability", desc: `Reliability is a system's ability to perform its intended function correctly over time, even in the face of component failures, software bugs, network partitions, and operator errors. It is broader than availability: an available system is running; a reliable system is running and producing correct results. A system can be highly available but unreliable (returning 200 OK with corrupt data) or temporarily unavailable but ultimately reliable (it fails safely and recovers to a consistent state). Google's SRE book defines reliability as the most important feature of a production service.

**How it works:**
- **Fault tolerance:** The system continues operating correctly even when components fail. Achieved through redundancy (multiple replicas), checksums (detecting data corruption), retries with idempotency (safe to retry without side effects), and circuit breakers (stopping cascading failures).
- **Data durability:** Data written to the system is not lost. Databases achieve durability via write-ahead logs (WAL), replication to multiple nodes, and periodic backups. Durability is separate from availability — a database replica might be temporarily unavailable but its data is durable on disk.
- **Graceful degradation:** When a dependency fails, the system serves a degraded but correct response rather than failing entirely. Netflix's Chaos Monkey tests whether services degrade gracefully when dependencies fail.
- **Idempotency:** Operations can be retried safely without duplicating side effects. Critical for reliable distributed systems where messages may be delivered multiple times. POST /payment should be idempotent (use idempotency keys); GET /balance is naturally idempotent.
- **Testing reliability:** Chaos engineering (deliberately injecting failures in production), disaster recovery drills, and load testing under adverse conditions all build confidence in reliability. Systems that have never been tested under failure often fail unexpectedly in production.

**Real-world example:** Amazon DynamoDB guarantees 99.999% availability and eleven nines of data durability (99.999999999%). Durability is achieved by replicating each piece of data across three availability zones using a consensus protocol. A write is not acknowledged until a majority of replicas confirm it — meaning even if two zones simultaneously fail, no acknowledged write is lost. The distinction between availability (99.999%) and durability (11 nines) is critical: durability is much harder to achieve and is essentially a one-way door (lost data cannot be recovered).

**Key takeaway:** Design for failure as the normal operating condition, not the exception. Assume every external call can fail, every disk can corrupt, and every operator can make mistakes. Build in retries (with backoff and jitter), idempotency, checksums, and circuit breakers from the start. The difference between a reliable system and an unreliable one is usually not the presence of failures but how the system responds to them.` },
    { id: 4, name: "Latency vs Throughput vs Bandwidth", desc: `Latency, throughput, and bandwidth are the three fundamental performance dimensions of a system, and confusing them leads to incorrect optimization efforts. A system can have high bandwidth but terrible latency (a truck full of hard drives — high capacity, slow to arrive). It can have low latency but low throughput (a fast response that can only serve one user at a time). Understanding which dimension is the bottleneck tells you where to invest optimization effort.

**How it works:**
- **Latency:** The time elapsed from when a request is sent to when a response is received. Composed of: network propagation delay (distance / speed of light), transmission delay (packet size / bandwidth), processing time (server computation), and queuing delay (waiting behind other requests). Measured in milliseconds. Optimized by: reducing round trips, using CDNs (geographic proximity), keeping request payloads small, and optimizing server-side processing.
- **Throughput:** The number of requests (or operations, or bytes) processed per unit of time — requests/second, transactions/second, MB/s. A system's throughput is limited by its bottleneck resource (CPU, network, disk, or a slow dependency). Throughput is increased by parallelism (more servers, more threads) and by eliminating bottlenecks.
- **Bandwidth:** The maximum rate at which data can be transferred over a network link — the theoretical ceiling. Bandwidth is a property of the network infrastructure; throughput is what you actually achieve (always ≤ bandwidth due to protocol overhead, congestion, and retransmissions).
- **The relationship:** Little's Law connects them: L = λW (average concurrent requests = throughput × average latency). If latency doubles and throughput stays constant, the number of concurrent requests in the system doubles — meaning you need double the resources to keep up.
- **Latency numbers everyone should know:** L1 cache ~1ns, main memory ~100ns, SSD read ~100μs, HDD read ~10ms, network within same datacenter ~0.5ms, cross-continental network ~150ms. These anchor back-of-the-envelope calculations.

**Real-world example:** Google found that adding 500ms of latency to search results caused a 20% drop in traffic — users are extraordinarily sensitive to latency. This drove Google's investment in global network infrastructure, CDN edge nodes, and preloading predictions. Meanwhile, Google's Bigtable was designed for throughput (millions of read/write operations per second) over low latency — the right trade-off for batch analytics workloads versus interactive search.

**Key takeaway:** Profile before optimizing — measure actual latency percentiles (p50, p95, p99) and throughput under load. P99 latency (the slowest 1% of requests) often reveals infrastructure problems invisible in averages. Optimize latency for interactive user-facing services; optimize throughput for batch processing and data pipelines. Never assume bandwidth is your bottleneck without measuring.` },
    { id: 5, name: "Fault Tolerance", desc: `Fault tolerance is a system's ability to continue operating correctly when one or more of its components fail. In a distributed system at scale, component failures are not exceptional events — they are continuous background noise. Servers crash, disks fail, network packets are dropped, and third-party APIs return errors. Fault-tolerant systems treat failure as the normal operating condition and engineer around it. The goal is not to prevent failures (impossible at scale) but to isolate them and prevent them from propagating.

**How it works:**
- **Redundancy:** Every critical component has a backup. Active-active redundancy (multiple instances serve traffic simultaneously — failure of one reduces capacity but doesn't stop service). Active-passive redundancy (standby replica takes over on failure — brief interruption but simpler). The number of simultaneous failures a system can tolerate is expressed as its fault tolerance level (N+1, N+2, etc.).
- **Replication:** Data is stored on multiple nodes so no single disk or server failure loses data. Replication factor of 3 (three copies) is the common default — tolerates one failure with consensus still possible.
- **Circuit breakers:** When a dependency is failing, stop sending it requests rather than queueing up more. The circuit "trips" open after a failure threshold, returns errors immediately (fast failure), and periodically probes whether the dependency has recovered. Prevents cascading failures where a slow dependency brings down its callers.
- **Bulkheads:** Isolate components so failure in one doesn't cascade to others. Separate thread pools, connection pools, and resource limits per dependency. Named after the watertight compartments in ship hulls — a breach in one compartment doesn't sink the ship.
- **Chaos engineering:** Netflix's Chaos Monkey deliberately kills random production instances. Chaos Kong kills entire availability zones. The discipline — intentionally introducing failures to discover weaknesses — builds genuine fault tolerance rather than assumed fault tolerance.

**Real-world example:** Kafka achieves fault tolerance by replicating each partition across multiple brokers (configurable replication factor, typically 3). Each partition has a leader and followers. All writes go to the leader; followers replicate asynchronously. If the leader fails, a new leader is elected automatically from the in-sync replicas (ISR). Kafka consumers track their own offsets, so they can resume from the exact position they left off after any failure. The system handles broker failures, network partitions, and slow consumers without losing messages or requiring operator intervention.

**Key takeaway:** Design for N+1 (minimum) or N+2 (recommended for critical systems) redundancy at every layer. Implement circuit breakers around every external dependency. Automate failover so humans don't need to be in the loop. Run chaos experiments in production (starting with low-traffic hours) to validate that your fault tolerance actually works — untested fault tolerance is assumption, not engineering.` },
    { id: 6, name: "High Availability vs Fault Tolerance", desc: `High Availability (HA) and Fault Tolerance (FT) are often used interchangeably, but they represent different engineering goals with different cost profiles. Both deal with keeping systems operational during failures, but HA accepts brief interruptions (measured in seconds) while FT requires continuous operation with zero interruption. Choosing between them depends on the business requirement — and FT's cost premium is significant enough that most systems target HA rather than true FT.

**How it works:**
- **High Availability (HA):** Minimizes downtime through rapid failure detection and fast failover. When a primary component fails, a backup takes over — but there is a brief interruption during the switchover (seconds to minutes). Achieved via load balancers with health checks, database failover (PostgreSQL's Patroni, MySQL's Orchestrator), and redundant infrastructure. Targets 99.9% to 99.99% uptime. Cost: moderate (N+1 redundancy, automated failover tooling).
- **Fault Tolerance (FT):** Ensures zero service interruption even during component failures. Requires active-active configurations where multiple components serve the same requests simultaneously — if one fails, others absorb its load instantly with no switchover delay. Requires more sophisticated consensus protocols, distributed coordination, and significantly more hardware. Targets 99.999%+ uptime. Cost: high (often 3× or more hardware vs non-redundant).
- **The spectrum:** Most real systems fall on a spectrum between HA and FT. Stateless web tier is naturally fault-tolerant (load balancers route around failed instances instantly). Databases typically target HA (primary/replica with automated failover). Payment processing systems target fault tolerance (no transaction can be lost or doubled).
- **Recovery time objective (RTO):** HA systems have an RTO of seconds to minutes (time to detect failure and complete failover). FT systems have an RTO of zero — recovery is instantaneous because no failover is needed.
- **Detection vs prevention:** HA relies on detecting failures and recovering. FT relies on running redundant paths simultaneously so there is nothing to recover from.

**Real-world example:** Google Spanner achieves fault tolerance for a globally distributed database by using synchronous Paxos replication — writes are only committed once a majority of replicas in multiple datacenters confirm them. A datacenter going offline does not interrupt writes because the remaining majority can still form consensus. This is true fault tolerance for the data layer. By contrast, most PostgreSQL deployments use HA — a primary with one or more hot standbys, where a DBA or automation tool promotes a standby if the primary fails, with 30–60 seconds of interruption.

**Key takeaway:** Target HA for most systems — it provides 99.9–99.99% uptime at a reasonable cost. Reserve FT for components where even seconds of interruption are unacceptable and cost is justified: payment processing, telecommunications switching, air traffic control systems. For web applications, a 30-second failover is typically acceptable. The extra engineering and hardware cost of true fault tolerance rarely delivers proportional business value.` },
    { id: 7, name: "Single Point of Failure (SPOF)", desc: `A Single Point of Failure (SPOF) is any component in a system whose failure causes the entire system to become unavailable. SPOFs are the enemy of availability — a system is only as reliable as its most fragile, unreplicated component. Identifying and eliminating SPOFs is one of the first exercises in designing a reliable system. The challenge is that SPOFs are not always obvious: they can be hardware, software, configuration, human dependencies, or even organizational bottlenecks like "only one engineer understands this service."

**How it works:**
- **Finding SPOFs:** Draw a dependency graph of your system. For each component, ask: "If this fails, what stops working?" Any answer of "everything" or "the entire user-facing service" identifies a SPOF. Common SPOFs: a single database server, a single load balancer, a single DNS provider, a single network switch, a single deployment server, or a single region.
- **Eliminating SPOFs through redundancy:** Replace each SPOF with an N+1 or N+2 configuration. Load balancers in active-active pairs. Database primaries with hot standbys and automated failover. DNS with multiple resolvers. Network switches in stacked configurations. The key is that redundancy must include automated failover — manual intervention means human SPOF.
- **Hidden SPOFs:** Shared infrastructure creates hidden SPOFs. If service A and service B both depend on the same database, a database failure creates a SPOF for both. Shared configuration stores, shared message brokers, and shared authentication services are common hidden SPOFs in microservice architectures.
- **Geographic SPOFs:** Deploying in a single availability zone or region creates a geographic SPOF. Power failures, cooling failures, and network outages affect entire AZs. Multi-AZ deployment eliminates intra-region SPOFs; multi-region eliminates regional SPOFs.
- **Software SPOFs:** A bug in shared code that all services depend on can be a software SPOF — if library version X has a critical bug and all services use it, a triggered bug brings down all services simultaneously. Dependency isolation and staggered deployments mitigate software SPOFs.

**Real-world example:** The 2017 AWS S3 outage in us-east-1 was triggered by an operator running a command that removed a larger set of servers than intended from the S3 subsystem handling billing. Because so many AWS services (and therefore so many internet companies) depended on a single S3 region, the failure cascaded: CloudFront, EC2, Elastic Beanstalk, and hundreds of major websites went down. S3 in us-east-1 was a de facto SPOF for much of the internet — a sobering example of how seemingly redundant cloud services can still harbor SPOFs at the ecosystem level.

**Key takeaway:** Build a SPOF inventory for your system — list every component and its redundancy level. Prioritize eliminating SPOFs in the order of their blast radius (how much of the system fails if they fail). Automated failover is non-negotiable: a redundant component with manual failover is a SPOF with extra steps. Include people and processes in your SPOF analysis — a team where only one person can deploy is an organizational SPOF.` },
    { id: 8, name: "Disaster Recovery", desc: `Disaster Recovery (DR) is the set of policies, tools, and procedures to enable the recovery of critical systems and data after a catastrophic failure — a complete datacenter loss, a ransomware attack, accidental mass data deletion, or a major cloud provider outage. DR goes beyond high availability (which handles individual component failures) to address scenarios where an entire site or region becomes unavailable. The defining metrics are RPO and RTO, which translate business requirements into measurable engineering targets.

**How it works:**
- **Recovery Point Objective (RPO):** The maximum acceptable amount of data loss measured in time. If RPO is 1 hour, you can afford to lose up to 1 hour of data in the worst case. RPO drives backup frequency and replication strategy. RPO = 0 requires synchronous replication; RPO = 24 hours allows nightly backups.
- **Recovery Time Objective (RTO):** The maximum acceptable downtime from disaster declaration to service restoration. RTO = 4 hours means the system must be functional within 4 hours of a disaster. RTO drives infrastructure investment — a 4-hour RTO can be met with backup-based recovery; a 15-minute RTO requires warm standby infrastructure.
- **DR strategies (cost vs recovery time tradeoff):**
- **Backup and restore:** Cheapest. Restore from backups when disaster strikes. RTO: hours to days. RPO: last backup (hours to days).
- **Pilot light:** A minimal version of the system runs in the DR region (just database replication, no application servers). Scale up application tier when needed. RTO: minutes to hours. RPO: seconds to minutes.
- **Warm standby:** A scaled-down version of the full production system runs continuously in DR region. Scale up to full capacity on failover. RTO: minutes. RPO: seconds.
- **Active-active (multi-site):** Full production capacity runs in multiple regions simultaneously. Traffic routed to healthy regions on failure. RTO: near zero. RPO: near zero. Most expensive.
- **DR testing:** A DR plan is only as good as its last successful test. Regular "disaster drills" — actually failing over to DR and running workloads there — are essential. An untested DR plan frequently fails when needed.

**Real-world example:** GitLab's 2017 database incident is a canonical DR lesson: a database administrator accidentally deleted the wrong PostgreSQL directory on the primary server. They discovered that their backups were not being verified (restore tests had never been run), their replication to secondary had stopped 6 hours prior (unnoticed), and their DR procedures were untested. They lost 6 hours of production data and were down for 18 hours. The incident led to publicly documented improvements in backup verification, monitoring, and DR testing — and GitLab's radical transparency in publishing the incident report became an industry model for post-mortems.

**Key takeaway:** Define RPO and RTO before designing DR — these numbers drive all architectural decisions. Test your DR plan at least quarterly; the only way to know it works is to run it. Verify backups continuously (not just that they're created, but that they can be restored). Start with warm standby if active-active is too costly — it provides a good balance of recovery speed and cost. The question is not "will we ever need DR?" but "when we need it, will it work?"` },
    { id: 9, name: "Back-of-the-Envelope Estimation", desc: `Back-of-the-envelope estimation is the practice of quickly calculating rough but reasonable capacity numbers for a system design — without a calculator, in an interview or planning meeting, in under a few minutes. The goal is not precision but order of magnitude: knowing whether you need 1 server or 1,000 servers, 1 GB of storage or 1 PB, 100 QPS or 1 million QPS. These estimates drive architectural decisions — a system handling 1,000 QPS needs a very different architecture than one handling 1 million QPS.

**How it works:**
- **Key numbers to memorize:**
- Traffic: 1M daily active users × 10 requests/day = 10M req/day ÷ 86,400 sec/day ≈ 116 QPS average, ~1,160 QPS at peak (10× average)
- Storage: 1M users × 1 photo/day × 500KB/photo = 500 GB/day. × 365 = ~180 TB/year
- Bandwidth: 1M users × 10KB/request × 100 QPS = 1 GB/s outbound
- A single server: handles ~1,000–10,000 QPS (simple reads); 100–1,000 QPS with DB writes; 10–100 QPS for compute-heavy requests
- A PostgreSQL instance: handles ~10,000 simple reads/sec, ~1,000–5,000 writes/sec
- **Estimation process:** (1) Clarify scale: daily active users, read/write ratio, data size. (2) Calculate QPS: users × actions/day / 86,400. (3) Calculate storage growth: new data per day × retention. (4) Calculate bandwidth: QPS × average request/response size. (5) Estimate servers: total QPS / QPS per server.
- **Power of 2 approximations:** 1,000 ≈ 10^3 (kilo), 1,000,000 ≈ 10^6 (mega), 10^9 (giga), 10^12 (tera). Approximate freely: 86,400 sec/day ≈ 10^5, 10M ÷ 10^5 = 100 QPS.
- **Read/write ratio:** Most systems are read-heavy (10:1 to 100:1). Estimate reads and writes separately — they have different scaling strategies.
- **When to scale:** One server → add caching when DB becomes bottleneck → add read replicas → add more app servers → consider sharding when a single DB can't handle write volume.

**Real-world example:** Twitter in 2013 handled ~400M tweets/day. 400M ÷ 86,400 ≈ 4,600 tweets/second written. Each tweet is read by followers: average user has ~200 followers, so 4,600 × 200 = 920,000 timeline insertions/second. This fan-out calculation immediately reveals why Twitter's home timeline delivery is the hard problem — and why they built a hybrid push/pull model (push for users with <10,000 followers; pull from celebrities' feeds on read) rather than simple fan-out.

**Key takeaway:** Practice these estimates until they're instinctive. The key numbers: 100K seconds/day (≈ 86,400), 1 server ≈ 10K simple QPS, 1 GB ≈ 10^9 bytes, network latency same DC ≈ 1ms, cross-continental ≈ 100ms. In interviews and design sessions, show your reasoning, not just your answer — the process demonstrates architectural thinking. Being off by 2× is fine; being off by 100× indicates a wrong assumption worth investigating.` },
    { id: 10, name: "SLAs, SLOs, SLIs", desc: `SLAs, SLOs, and SLIs form a hierarchy for defining, measuring, and enforcing reliability commitments — from the raw metric (SLI) to the internal target (SLO) to the external contract (SLA). They are the operational language of reliability: without them, "the system should be fast and reliable" is a vague aspiration; with them, it becomes a measurable, accountable commitment. Google's Site Reliability Engineering practice codified this framework and it has become the industry standard for production systems.

**How it works:**
- **Service Level Indicator (SLI):** A specific, measurable metric that reflects service quality. Examples: availability (% of successful HTTP responses), latency (% of requests completing under 200ms), error rate (% of requests returning 5xx), throughput (requests/second). SLIs are the raw measurements — they tell you what the system is actually doing right now.
- **Service Level Objective (SLO):** An internal target for an SLI, expressed as a percentage over a time window. "99.9% of requests complete in under 200ms over a 30-day rolling window." "99.95% of requests return non-5xx responses." SLOs are commitments to your own team — they define what "good enough" means and trigger action when violated. SLOs should be ambitious but achievable with normal engineering investment.
- **Service Level Agreement (SLA):** An external contract with a customer that specifies minimum SLO levels and consequences for violation (credits, refunds, contract exit rights). SLAs are typically looser than internal SLOs — if your SLO is 99.9%, your SLA might commit to 99.5%, giving a buffer. Violating an SLA has financial and legal consequences; violating an SLO triggers internal engineering response.
- **Error budgets:** The complement of an SLO. If the SLO is 99.9% availability, the error budget is 0.1% — about 43 minutes/month. If the error budget is exhausted, new feature deployments stop until the budget replenishes. This creates a structured tension between shipping velocity and reliability.
- **Choosing SLIs:** Not every metric should be an SLI — choose the metrics that best reflect user experience. Availability and latency are almost always SLIs for user-facing services. Correctness (are the results right?) is often overlooked but critical for data pipelines.

**Real-world example:** Google Cloud Storage publishes an SLA of 99.95% monthly uptime for the Standard storage class. Internally, Google targets a higher SLO (perhaps 99.99%) so they have headroom before the SLA is violated. Each team managing a GCS dependency has error budgets derived from their SLOs — when an error budget is close to exhaustion, the team freezes risky changes and focuses on reliability. This framework prevented Google SREs from having arbitrary arguments about "is this safe to ship?" — the error budget answered objectively.

**Key takeaway:** Define SLIs before building, not after. Choose SLIs that directly reflect user experience (latency at p95/p99, not average; error rate, not uptime). Set SLOs that are meaningful to the business. Make error budgets explicit — they transform reliability from a vague aspiration into a concrete, finite resource that engineering teams manage deliberately. If you're not measuring it, you're not managing it.` },
  ],
};
export default fundamentals;
