const javascriptCore = {
  name: "JavaScript Core",
  icon: "⬢",
  color: "#F7DF1E",
  concepts: [
    { id: 30, name: "ES6+ Features", desc: `ES6 (ECMAScript 2015) was the most significant update to JavaScript in its history — transforming it from a scripting language into a full-featured programming language capable of powering large-scale applications. The features introduced in ES6 and subsequent annual releases (ES2016 through ES2025) are not syntactic candy; they represent fundamental patterns that every professional JavaScript developer uses daily. Understanding which features exist and when to reach for them is the foundation of modern JavaScript fluency.

**How it works:**
- **Arrow functions:** Concise syntax (x => x * 2) and lexical this binding — the this inside an arrow function is always the this of the enclosing scope, solving the classic callback this problem. Arrow functions cannot be used as constructors and have no arguments object.
- **Destructuring:** Extract values from objects and arrays into named variables. const { name, age = 0 } = user (with default). const [first, ...rest] = items. Function parameter destructuring: function render({ title, body }) {}. Eliminates repetitive property access chains.
- **Template literals:** Backtick strings with embedded expressions (\`Hello, \${name}!\`), multi-line support without \n, and tagged templates (html\`<div>\${content}</div>\`) for DSL-style string processing.
- **Spread and rest:** Spread (...arr) expands an iterable into individual arguments or elements. [...a, ...b] merges arrays; {...obj, key: val} merges objects (shallow). Rest (...args) collects remaining parameters into an array.
- **Classes:** Syntactic sugar over prototypal inheritance. class Animal { constructor(name) { this.name = name } speak() { ... } }. class Dog extends Animal { speak() { super.speak(); ... } }. Private fields (#field), static methods, and accessors (get/set) are supported.
- **Optional chaining and nullish coalescing (ES2020):** user?.address?.city safely traverses potentially-null chains without throwing. value ?? 'default' returns 'default' only if value is null or undefined (not for 0, '', or false — unlike ||).
- **Promise.allSettled, Array.at(), Object.hasOwn(), structuredClone():** Each annual ES release adds targeted utilities that address specific pain points — knowing the standard library reduces dependency on utility libraries.

**Real-world example:** Airbnb's JavaScript style guide, adopted by thousands of teams, mandated ES6+ features across their entire frontend codebase in 2015 — arrow functions, const/let, destructuring, template literals, and modules. Their internal metrics showed a 30% reduction in lines of code for equivalent functionality and a measurable decrease in callback-related bugs (the "this gotcha" and callback nesting problems) after the migration.

**Key takeaway:** Learn ES6 core (arrows, destructuring, spread, classes, modules, promises) as table stakes. Then learn optional chaining, nullish coalescing, and Promise combinators (all, allSettled, race, any) as the next priority. Track TC39 proposals at github.com/tc39/proposals — Stage 3 proposals are safe to use with a transpiler; Stage 4 are in the spec.` },
    { id: 31, name: "Closures", desc: `A closure is a function that remembers and retains access to variables from its outer (enclosing) scope, even after the outer function has finished executing and its local scope would normally be garbage-collected. Closures are not a feature you opt into — they are how JavaScript functions work by default. Every function in JavaScript is a closure over the scope in which it was created. Understanding closures is understanding JavaScript's memory model and the foundation of nearly every advanced pattern in the language.

**How it works:**
- **The mechanism:** When a function is created, it captures a reference to its lexical environment — all variables in scope at the point of creation. When the function is later called, it accesses those variables through this captured reference, not through any re-execution of the outer scope. The variables persist as long as any closure referencing them exists.
- **Canonical example:** function makeCounter() { let count = 0; return { increment() { count++ }, get() { return count } } }. The returned object's methods close over count. count is not accessible from outside but persists across calls because the methods hold a reference to the environment containing it.
- **Data privacy:** Closures are JavaScript's primary mechanism for encapsulation before classes with private fields. Module pattern: const module = (function() { let private = 0; return { getPrivate: () => private } })() — an IIFE creating a private scope, returning public interface.
- **Partial application and currying:** function multiply(x) { return y => x * y }. const double = multiply(2) closes over x=2. double(5) returns 10. Closures enable functions to be partially configured and reused.
- **The classic loop bug:** for (var i = 0; i < 3; i++) { setTimeout(() => console.log(i), 100) } logs 3, 3, 3 — not 0, 1, 2. All three callbacks close over the same var i, which is 3 by the time they execute. Fix: use let (block-scoped, creates a new binding per iteration) or wrap in an IIFE to create per-iteration scope.
- **Memory implications:** Closures prevent garbage collection of closed-over variables as long as any referencing function exists. Event listeners that close over large objects prevent those objects from being collected — a common source of memory leaks.

**Real-world example:** React hooks are built on closures. When you write useState(), the state value and setter are captured in the closure of every render function call. useEffect(() => { fetchData(userId) }, [userId]) — the effect callback closes over userId from the current render. React's hooks API would be impossible without closures; they are how React maintains per-render isolated state without explicit object references.

**Key takeaway:** When debugging unexpected variable values in callbacks, event handlers, or async code, suspect closure scope. Ask: "What scope was this function created in, and what were the values there?" The answer reveals what the function sees. Understanding closures also explains React's stale closure problem — why a hook callback "sees" old state values.` },
    { id: 32, name: "Promises & Async/Await", desc: `Promises and async/await are JavaScript's solution to asynchronous programming — operations that take time to complete (network requests, file I/O, timers) without blocking the thread. Before Promises (pre-ES6), asynchronous code was written with callbacks, leading to deeply nested "callback hell" that was difficult to read, debug, and handle errors in. Promises introduced a composable, chainable abstraction; async/await made asynchronous code read like synchronous code while keeping it non-blocking.

**How it works:**
- **Promise states:** A Promise is an object representing an eventual value. It starts pending, then settles to either fulfilled (with a value) or rejected (with a reason). Once settled, it never changes state. promise.then(value => ...) handles fulfillment; promise.catch(err => ...) handles rejection; promise.finally(() => ...) runs either way.
- **Promise chaining:** .then() returns a new Promise — enabling chaining. fetch(url).then(res => res.json()).then(data => process(data)).catch(err => handle(err)). Each .then() receives the resolved value of the previous step; errors propagate to the nearest .catch().
- **async/await:** An async function always returns a Promise. Inside an async function, await pauses execution until the awaited Promise settles, then returns its resolved value (or throws its rejection reason). The code reads sequentially but executes asynchronously. try/catch handles rejections naturally.
- **Promise combinators:** Promise.all([p1, p2, p3]) resolves when all resolve (rejects if any rejects — fail-fast). Promise.allSettled([p1, p2]) waits for all to settle regardless of outcome — returns array of {status, value/reason}. Promise.race([p1, p2]) resolves/rejects with the first to settle. Promise.any([p1, p2]) resolves with the first fulfillment (rejects only if all reject).
- **Microtask queue:** Resolved Promise callbacks (.then handlers) are placed in the microtask queue, which runs after the current synchronous task but before any macrotasks (setTimeout, I/O). This means Promise resolution is always asynchronous, even if the Promise was already resolved.
- **Common mistakes:** Forgetting to return in .then() chains (breaks the chain), floating Promises (not awaiting or returning, errors are silently swallowed), await inside forEach (doesn't await — use for...of or Promise.all with .map() instead).

**Real-world example:** GitHub's frontend makes dozens of concurrent API requests when loading a repository page — contributors, commits, issues, pull requests, languages. Their implementation uses Promise.all() to fire all requests simultaneously and await the combined result, reducing the total load time from sum-of-all-requests (sequential) to max-of-all-requests (parallel). For typical responses, this reduces the data loading phase from ~2s to ~400ms.

**Key takeaway:** Prefer async/await over raw .then() chains for readability in most cases. Use Promise.all() for independent parallel operations — it's the single most impactful async performance technique. Always handle Promise rejection — unhandled rejections crash Node.js and produce console errors in browsers. Never use await inside Array.forEach.` },
    { id: 33, name: "Event Loop", desc: `JavaScript is single-threaded — it can execute only one piece of code at a time. Yet it handles concurrent operations: network requests, timers, and user events all proceed without blocking the page. The event loop is the mechanism that makes this possible. Understanding it precisely is the difference between writing JavaScript that behaves intuitively and debugging mysterious timing bugs and UI freezes.

**How it works:**
- **The call stack:** JavaScript executes code by pushing function calls onto a stack and popping them when they return. While any frame is on the stack, no other code can run. A synchronous infinite loop (while(true) {}) permanently blocks the stack — no events fire, no renders happen.
- **The task queue (macrotask queue):** setTimeout, setInterval, I/O callbacks, requestAnimationFrame, and user event callbacks (click, keydown) are scheduled as "tasks" in this queue. The event loop picks one task per loop iteration, runs it to completion on the call stack, then checks for more tasks.
- **The microtask queue:** Promise .then/.catch/.finally callbacks and queueMicrotask() are "microtasks." After every task completes, the event loop drains the entire microtask queue before picking the next task. This means microtasks have higher priority than macrotasks and run between tasks, not concurrently.
- **Execution order example:** console.log('1'); setTimeout(() => console.log('2'), 0); Promise.resolve().then(() => console.log('3')); console.log('4'). Output: 1, 4, 3, 2. Synchronous first (1, 4), then microtasks (3 — Promise), then macrotasks (2 — setTimeout, even with 0ms delay).
- **Rendering:** The browser's rendering pipeline (style/layout/paint) runs between tasks — it's like a special high-priority task. Long-running synchronous code (parsing 50,000 items in a loop) blocks rendering, causing visual "jank." requestAnimationFrame runs just before the render step, making it ideal for animation.
- **The "blocking" misconception:** await does not block the thread — it suspends the current async function and returns control to the event loop, allowing other code to run. The thread is never blocked; the async function is just paused until its awaited Promise resolves.

**Real-world example:** React's concurrent mode was built specifically to work with the event loop's task structure. React 18 uses scheduler.postTask() (or setTimeout fallback) to break rendering work into time-sliced chunks — each chunk is one task. Between chunks, the event loop can handle user input (maintaining responsiveness). This is why React 18's concurrent features prevent "input lag during heavy renders" — the rendering is interruptible by higher-priority user events.

**Key takeaway:** Two practical rules: (1) Never run long synchronous loops on the main thread — they freeze the UI; break heavy work into chunks with setTimeout(fn, 0) or use a Web Worker. (2) Promise callbacks run before setTimeout callbacks at equivalent "time" — use this when ordering of async operations matters. When debugging timing bugs, ask: "Is this in the microtask or macrotask queue?"` },
    { id: 34, name: "Prototypal Inheritance", desc: `JavaScript's inheritance model is prototype-based, not class-based. Every object has an internal [[Prototype]] link to another object (or null). When a property is not found on an object, JavaScript traverses the prototype chain — looking at the prototype, then the prototype's prototype, and so on — until it finds the property or reaches null. The class syntax (ES6+) is syntactic sugar over this underlying prototype mechanism, not a separate system.

**How it works:**
- **The prototype chain:** obj.__proto__ (non-standard but widely supported) or Object.getPrototypeOf(obj) returns an object's prototype. Property lookup traverses this chain: obj.toString() searches obj, then obj's prototype, then Object.prototype (which has toString), stopping there. If toString were overridden on obj itself, that would be found first (shadowing).
- **Object.create():** Object.create(proto) creates a new object with proto as its [[Prototype]]. const animal = { speak() { ... } }; const dog = Object.create(animal) creates dog with animal as its prototype. dog.speak() traverses to animal.speak. This is the pure prototypal inheritance pattern, without class syntax.
- **Constructor functions (pre-class):** function Person(name) { this.name = name } defines a constructor. Person.prototype.greet = function() { ... } adds shared methods to the prototype. new Person('Alice') creates an object with Person.prototype as its [[Prototype]], sets this.name, and returns the new object. All Person instances share the greet method via prototype (not per-instance copy).
- **class syntax desugaring:** class Animal { constructor(name) { this.name = name } speak() { ... } } is equivalent to: function Animal(name) { this.name = name } + Animal.prototype.speak = function() { ... }. The class keyword is purely syntax — typeof Animal is still "function."
- **instanceof:** obj instanceof Constructor checks if Constructor.prototype appears anywhere in obj's prototype chain — not if obj was created by Constructor specifically. Can be fooled by swapping prototypes.
- **hasOwnProperty vs in:** obj.hasOwnProperty('key') checks only the object itself, not the chain. 'key' in obj checks the object and its entire prototype chain. Use hasOwnProperty (or Object.hasOwn()) when you need to confirm a property is directly on an object.

**Real-world example:** JavaScript's built-in Array methods (map, filter, reduce, forEach) are defined on Array.prototype, not on each array instance. [1,2,3].map() traverses the prototype chain from the specific array instance to Array.prototype where .map lives. This is why you can add custom methods to Array.prototype (though doing so in production code is an anti-pattern) — they immediately become available on all arrays.

**Key takeaway:** Use class syntax for clarity — it's the modern standard and handles edge cases correctly. But understand that every class is built on prototypes: methods defined in a class body live on the prototype, not on instances. This matters for performance (one method on the prototype vs N method copies on N instances), for instanceof behavior, and for debugging prototype-chain issues.` },
    { id: 35, name: "this Keyword", desc: `this is one of JavaScript's most confusing features because it is not lexically scoped like other variables — its value is determined by how a function is called, not where it is defined. The same function can have a different this depending on the call site. Understanding the five binding rules for this and knowing which one applies is the key to eliminating an entire class of JavaScript bugs.

**How it works:**
- **Default binding:** In a regular function called without context (fn()), this is the global object (window in browsers) in non-strict mode, and undefined in strict mode. Strict mode is the default in ES modules, classes, and any file with "use strict."
- **Implicit binding:** When a function is called as a method (obj.fn()), this is obj — the object to the left of the dot. If the method is extracted and called without the object (const fn = obj.greet; fn()), implicit binding is lost and default binding applies. This is the "lost this" bug.
- **Explicit binding:** call(thisArg, ...args), apply(thisArg, [...args]), and bind(thisArg) explicitly set this. bind() returns a new function with this permanently fixed — useful for event handlers and callbacks. fn.call(obj) and fn.apply(obj) invoke immediately with specified this.
- **new binding:** When a function is called with new, JavaScript creates a new object, sets its [[Prototype]] to the constructor's prototype, sets this to the new object inside the constructor, and returns the new object (unless the constructor explicitly returns a different object).
- **Arrow function lexical binding:** Arrow functions do not have their own this — they inherit this from the enclosing lexical scope at definition time. class Timer { start() { setInterval(() => this.tick(), 1000) } } — the arrow function's this is the Timer instance, not the setInterval context. This makes arrow functions the natural choice for callbacks where you need the outer this.
- **Priority:** new > explicit (bind/call/apply) > implicit (method call) > default. Arrow functions are exempt — they bypass all binding rules.

**Real-world example:** React class component lifecycle methods famously required explicit binding: this.handleClick = this.handleClick.bind(this) in the constructor, or using class field arrow functions (handleClick = () => {}). This was such a common source of bugs — forgetting to bind causing TypeError on this.setState — that it was cited as a major motivation for React hooks, which avoid this entirely by using closures instead.

**Key takeaway:** In modern JavaScript: use arrow functions for callbacks and class methods (avoiding this binding headaches), use class field arrow functions instead of constructor binding, and use explicit bind() when you must pass a method as a callback from a regular function context. When this behaves unexpectedly, add console.log(this) at the call site — the binding rule that applies becomes immediately obvious.` },
    { id: 36, name: "Scope & Hoisting", desc: `Scope determines where variables are accessible in code; hoisting is JavaScript's behavior of conceptually moving variable and function declarations to the top of their scope before execution. Together they explain some of JavaScript's most surprising behaviors — variables that exist before they appear to be declared, functions that can be called before their definition in the file, and the behavior differences between var, let, and const.

**How it works:**
- **Scope types:** Global scope (accessible everywhere), function scope (accessible only within the function), and block scope (accessible within the {} block — introduced with let and const in ES6). The scope chain: inner scopes have access to outer scope variables, but not vice versa.
- **var hoisting:** var declarations are hoisted to the top of their enclosing function scope and initialized to undefined. console.log(x); var x = 5 runs as: var x = undefined; console.log(x) — logs undefined, not an error. var is also function-scoped, not block-scoped: an if block's var leaks into the enclosing function.
- **let and const — Temporal Dead Zone (TDZ):** let and const are hoisted to the top of their block scope but are not initialized. Accessing them before their declaration line throws ReferenceError: Cannot access 'x' before initialization. This "temporal dead zone" prevents the confusing undefined behavior of var while preserving hoisting's internal mechanism.
- **Function declaration hoisting:** function greet() { return 'Hello' } is fully hoisted — the entire function body is available at the top of its scope. greet() can be called before the function declaration appears in the file. This is different from function expressions (const greet = function() {}) and arrow functions (const greet = () => {}), which are not hoisted.
- **const ≠ immutable:** const prevents reassignment of the variable binding, not mutation of the value. const arr = [1,2,3]; arr.push(4) — valid. const arr = [5] — TypeError. For objects and arrays, const only guarantees the reference doesn't change; the contents remain mutable. Use Object.freeze() for shallow immutability.
- **let vs const:** Prefer const by default for everything that doesn't need reassignment. Use let for loop counters, accumulators, and values explicitly reassigned. Never use var in modern code — its function scope and hoisting behavior produce bugs that block scope eliminates.

**Real-world example:** The V8 JavaScript engine (Chrome, Node.js) optimizes const declarations more aggressively than let — it can assume the binding won't change and avoid re-checking. Airbnb's ESLint configuration enforces prefer-const as a lint rule, requiring justification for any let declaration. Their code review guidelines document that using const by default also communicates intent: "this value doesn't change" is information for the next developer reading the code.

**Key takeaway:** Use const by default; use let only when reassignment is required; never use var. Understand TDZ — ReferenceError before declaration is expected behavior for let/const, not a bug. Know that function declarations are fully hoisted (callable anywhere in scope) while function expressions are not — this matters for code organization in files without modules.` },
    { id: 37, name: "Modules (ESM vs CommonJS)", desc: `JavaScript modules are self-contained files that explicitly declare what they export and what they import from other files — eliminating the global namespace pollution and implicit dependency ordering that plagued pre-module JavaScript. Two module systems exist: CommonJS (Node.js's original system, using require/module.exports) and ES Modules (the native browser and modern Node.js standard, using import/export). Understanding both and their differences is essential for working across the full JavaScript ecosystem.

**How it works:**
- **ES Modules (ESM):** import and export are keywords. Named exports: export const PI = 3.14; export function add(a,b) {}, imported as import { PI, add } from './math.js'. Default export: export default function App() {}, imported as import App from './App.jsx'. Static — imports must be at the top level, not inside conditions or functions, enabling static analysis at build time.
- **Dynamic import():** import('./module.js').then(m => m.default()) is a function call returning a Promise — enables code splitting and conditional loading. Works in both ESM and CommonJS contexts. Used by bundlers (Vite, webpack) to create separate chunks loaded on demand.
- **CommonJS (CJS):** require() and module.exports. const path = require('path'). module.exports = { add, subtract }. Dynamic by nature — require() can appear anywhere. Synchronous — the module is loaded, executed, and returned before the next line. Node.js's original module system; still used in many packages and Node.js scripts.
- **Key differences:** ESM is live bindings — importing a named export gives you a live view of its current value; CJS copies the value at require time. ESM is statically analyzable — build tools can determine at build time exactly what is imported and tree-shake unused exports. CJS require() can be dynamic (require(someVariable)) making static analysis impossible.
- **Interoperability:** ESM can import CJS modules (the module.exports becomes the default export). CJS cannot require() ESM (async vs sync mismatch) — this is the "ESM-only package" problem that caused controversy when packages like chalk, node-fetch, and others went ESM-only.
- **Node.js ESM:** Add "type": "module" to package.json (all .js files treated as ESM) or use .mjs extension. Node.js fully supports ESM as of v12+; dual CJS/ESM packages use the exports field in package.json.

**Real-world example:** When Lodash released tree-shakeable ESM exports (lodash-es), bundle sizes for applications importing Lodash shrank dramatically. An application importing import { debounce } from 'lodash-es' bundles only debounce (2KB) versus importing the full 70KB CJS Lodash bundle that require('lodash') forces. The shift to ESM reduced average JavaScript bundle sizes by 15–30% for Lodash-heavy applications — purely from the static analysis enabling tree-shaking.

**Key takeaway:** Use ESM (import/export) for all new code — browsers support it natively, bundlers optimize it better, and it's the direction the ecosystem is moving. Know CommonJS for reading legacy code and Node.js scripts. Understand that tree-shaking works only with ESM — importing from CJS packages imports the entire package regardless of how much you use.` },
    { id: 38, name: "Destructuring & Spread", desc: `Destructuring and spread are ES6 syntax extensions that make working with arrays, objects, and function parameters dramatically more concise and expressive. They appear in virtually every modern JavaScript codebase — in React component props, API response handling, function signatures, and array manipulation. Mastering them removes the repetitive property-access patterns that cluttered pre-ES6 JavaScript and reveals the intent of code more clearly.

**How it works:**
- **Object destructuring:** const { name, age, address: { city } } = user extracts multiple properties in one statement with nested destructuring. Rename: const { name: fullName } = user creates fullName. Default: const { role = 'user' } = options uses 'user' if role is undefined. In function parameters: function render({ title, body, author = 'Unknown' }) {} — no need to access props.title inside the function.
- **Array destructuring:** const [first, second, ...rest] = array — positional extraction with rest collection. Skip elements: const [, second] = array. Swap variables without temp: [a, b] = [b, a]. Useful with APIs that return arrays: const [data, error] = await someAPI().
- **Spread operator (...):** In arrays: [...arr1, ...arr2] — shallow merge. [...arr, newItem] — append without mutation. In objects: {...obj, key: 'new'} — shallow copy with override (last wins). {...defaults, ...userConfig} — merge configs. Spread copies references for nested objects, not deep values — it's a shallow copy.
- **Rest parameters:** function log(message, ...context) {} — context collects all arguments after message into an array. Replaces the old arguments object (which is not a real array). Works in destructuring too: const { id, ...rest } = user — rest contains all properties except id.
- **Optional chaining with destructuring:** const { address: { city } = {} } = user — default the nested object to {} to prevent destructuring null/undefined throwing. More explicitly: const city = user?.address?.city.
- **Destructuring in imports:** import { useState, useEffect } from 'react' is destructuring the module's named exports — the same syntax, applied to the module system.

**Real-world example:** Next.js server components use destructuring pervasively in their API. async function Page({ params, searchParams }) {} destructures the page's URL parameters and query string directly in the function signature. await fetch('/api/items').then(r => r.json()).then(({ items, total, page }) => ...) destructures the API response shape — the intent is immediately clear from the destructured names, whereas data.items, data.total, data.page repeats "data." three times and obscures the structure.

**Key takeaway:** Use destructuring for function parameters whenever the parameter is an object — it documents the expected shape and provides defaults. Use spread for shallow copies and merging — but remember it's shallow, not deep. Use rest parameters instead of the arguments object. These patterns appear in essentially all modern React, Vue, and Node.js code — fluency with them is baseline JavaScript competence.` },
    { id: 39, name: "Map, Set, WeakMap, WeakSet", desc: `Map and Set are ES6 data structures that solve limitations of plain objects and arrays for specific use cases. Map is a key-value store that accepts any value (including objects) as keys and preserves insertion order. Set is a collection of unique values. Their Weak variants (WeakMap, WeakSet) hold weak references to their keys, allowing garbage collection — enabling memory-safe metadata attachment to objects without preventing their cleanup.

**How it works:**
- **Map vs plain object:** Objects can only use strings and symbols as keys (non-string keys are coerced to strings). Map accepts any value as a key: map.set(domElement, {clicks: 0}) uses a DOM element as key — impossible with an object. Map preserves insertion order, has a .size property, and is iterable (for...of directly). Object.keys() returns only string-keyed own properties; Map iteration is always key-value pairs.
- **Map operations:** map.set(key, value), map.get(key), map.has(key), map.delete(key), map.size, map.clear(). Iterate: map.forEach((value, key) => ...) or for (const [key, value] of map). Convert: Map.from(Object.entries(obj)) to build from object; Object.fromEntries(map) to convert to object.
- **Set:** A collection of unique values — duplicates are silently ignored. new Set([1, 2, 2, 3]) creates {1, 2, 3}. set.add(value), set.has(value), set.delete(value), set.size. Remove duplicates: [...new Set(arr)]. Set intersection: new Set([...a].filter(x => b.has(x))). Unlike arrays, .has() on Set is O(1) not O(n).
- **WeakMap:** Keys must be objects (or registered symbols). The key is held weakly — if no other references to the key object exist, it can be garbage collected, and its WeakMap entry is removed automatically. Use cases: attaching private data to objects, component-to-metadata associations, memoization caches keyed on objects. No iteration (keys are not enumerable — they may be dead).
- **WeakSet:** A collection of objects held weakly. Useful for tracking object membership without preventing cleanup: seen.has(node) to avoid revisiting DOM nodes without keeping them alive.
- **WeakRef and FinalizationRegistry (ES2021):** WeakRef allows holding an object reference that doesn't prevent GC. FinalizationRegistry registers cleanup callbacks for when objects are collected. Together they enable advanced memory-sensitive caching patterns.

**Real-world example:** React's internal implementation uses WeakMap to associate component fiber metadata with host DOM elements — each DOM node that React manages has associated fiber data stored in a WeakMap keyed on the DOM element. This ensures that if a DOM element is removed from the document and dereferenced, the fiber data doesn't prevent garbage collection. The WeakMap pattern is specifically what allows React to avoid memory leaks when components unmount and their DOM nodes are removed.

**Key takeaway:** Reach for Map when: keys are not strings, insertion order matters for iteration, or you need a clean .size without the noise of prototype properties. Reach for Set for unique collections and O(1) membership testing. Use WeakMap when attaching metadata to objects you don't own (DOM elements, external objects) — it prevents memory leaks that a regular Map would cause by keeping keys alive indefinitely.` },
    { id: 40, name: "Proxy & Reflect", desc: `Proxy is an ES6 object wrapper that intercepts and redefines fundamental operations on the wrapped object — property access, assignment, deletion, function invocation, and more. Reflect is a companion object providing the default implementations of those same operations. Together, they enable meta-programming: code that observes, customizes, and validates other code's behavior without modifying it. Proxy is the engine behind Vue 3's reactivity, Immer's immutability, and many validation and API-mocking libraries.

**How it works:**
- **Creating a proxy:** new Proxy(target, handler). target is the original object; handler is an object defining "traps" — interceptors for fundamental operations. const proxy = new Proxy({}, { get(target, key) { return key in target ? target[key] : \`\${key} not found\` } }). Any property access on proxy invokes the get trap.
- **Available traps:** get (property access), set (property assignment), has (in operator), deleteProperty (delete keyword), apply (function call), construct (new operator), getPrototypeOf, setPrototypeOf, defineProperty, getOwnPropertyDescriptor, ownKeys, isExtensible, preventExtensions. Traps not defined in the handler pass through to the target directly.
- **Reflect:** Reflect.get(target, key, receiver), Reflect.set(target, key, value, receiver) — always call Reflect within traps to invoke the default behavior correctly (with proper prototype chain handling and strict mode compliance). Without Reflect, implementing transparent pass-through traps is error-prone.
- **Vue 3 reactivity:** Vue 3's reactive() wraps objects in Proxy. The get trap tracks dependencies (which components read this property); the set trap triggers re-renders when values change. This enables Vue's template system to automatically re-render only components that depend on changed reactive state — without requiring explicit subscriptions or setState calls.
- **Validation proxies:** Wrap an object with a Proxy that validates values in the set trap before allowing assignment. type-checking, range validation, or read-only enforcement can be applied transparently to any object.
- **Revocable proxies:** Proxy.revocable(target, handler) returns a {proxy, revoke} pair. Calling revoke() makes the proxy throw on any access — useful for capability-based access control, where a resource can be "expired" by revoking its proxy.

**Real-world example:** Immer (used extensively in Redux Toolkit and React state management) uses Proxy to implement "structural sharing" immutable state updates. immer.produce(state, draft => { draft.user.name = 'Alice' }) wraps state in a Proxy (the "draft"). Mutations to the draft are recorded via set traps; Immer then constructs a new state object sharing all unchanged nested objects and replacing only the changed ones. The Proxy makes mutable-looking code produce immutable output — without any deep clone performance cost.

**Key takeaway:** Proxy is a power tool — reach for it when you need transparent behavior modification of objects you don't own, or when implementing reactivity, validation, or access control. Always use Reflect in traps to maintain correct default behavior. The performance cost of a Proxy trap (vs direct property access) is typically 10–20% in microbenchmarks but negligible in real application code dominated by I/O.` },
    { id: 41, name: "Generators & Iterators", desc: `Generators are functions that can pause mid-execution and resume later, yielding a sequence of values on demand rather than computing and returning everything at once. Iterators are the protocol that any object can implement to make it work with for...of, spread, and destructuring. Together, they enable lazy evaluation — computing values only when needed — which is critical for large datasets, infinite sequences, and custom data traversal.

**How it works:**
- **Iterator protocol:** An object is iterable if it has a [Symbol.iterator]() method returning an iterator. An iterator has a next() method returning { value, done }. done: true signals the sequence is complete. Built-in iterables: Arrays, Strings, Maps, Sets, NodeLists, arguments. for...of, spread (...iter), and destructuring ([a, b] = iter) all consume iterators.
- **Generator functions:** function* gen() { yield 1; yield 2; yield 3 }. Calling gen() returns a generator object (which is both an iterator and an iterable). Calling .next() on it runs until the next yield, returns { value: yieldedValue, done: false }. After the last yield (or a return), next() returns { value: undefined, done: true }.
- **Generator as lazy sequence:** function* range(start, end, step = 1) { for (let i = start; i < end; i += step) yield i }. for (const n of range(0, 1000000)) { if (n > 10) break } — generates only 11 values, not 1,000,000. The sequence is computed on demand; unused values are never computed.
- **Two-way communication:** yield is an expression — it produces a value and receives a value. gen.next(inputValue) sends inputValue into the generator as the result of the yield expression. This enables generators to be used as coroutines — cooperative multitasking between a generator and its caller.
- **Async generators:** async function* asyncRange() { yield await fetch('/api/1'); yield await fetch('/api/2') }. for await (const result of asyncRange()) processes each yielded Promise sequentially. Used for streaming API responses, paginated data fetching, and processing server-sent event streams.
- **Delegating with yield*:** yield* otherGenerator() delegates iteration to another generator, forwarding all its yielded values. Enables composition of generators: function* combined() { yield* gen1(); yield* gen2() }.

**Real-world example:** Node.js streams and modern streaming APIs (ReadableStream) are conceptually generator-like. The Deno standard library implements lazy file reading using async generators: async function* readLines(path) { ... yield line }. A log processing script processing a 10GB log file uses for await (const line of readLines('massive.log')) — reading and processing line by line without loading the entire file into memory, using constant memory regardless of file size.

**Key takeaway:** Generators are most valuable for: (1) lazy sequences (generate values on demand, stop early), (2) infinite sequences (IDs, fibonacci), (3) async iteration (streaming data, paginated APIs). In React, generators underpin the redux-saga middleware pattern for complex async workflows. For most application code, Promises and async/await cover async needs; reach for generators when you need explicit flow control, lazy evaluation, or infinite sequences.` },
    { id: 42, name: "Web Workers", desc: `Web Workers run JavaScript in a background thread — completely separate from the main thread where the UI runs. Because JavaScript is single-threaded on the main thread, any expensive computation (image processing, cryptography, data parsing, machine learning inference) blocks rendering and makes the UI unresponsive. Web Workers move that computation off the main thread, keeping the UI fluid at 60fps while the heavy work proceeds in parallel.

**How it works:**
- **Creating a worker:** const worker = new Worker('./worker.js') spawns a background thread running worker.js. The worker script runs in a completely separate global context — no access to the DOM, document, or window. It has access to fetch, setTimeout, IndexedDB, WebSockets, and the Web Crypto API.
- **Message passing:** Communication is asynchronous via message passing. main thread: worker.postMessage(data). worker: self.onmessage = (e) => { const result = heavyComputation(e.data); self.postMessage(result) }. main thread: worker.onmessage = (e) => { handleResult(e.data) }. Data is copied (structured clone algorithm) between threads — no shared memory by default.
- **Structured clone:** Messages are deep-copied using the structured clone algorithm — which supports more types than JSON.stringify (dates, maps, sets, typed arrays, circular references) but cannot clone functions, DOM nodes, or class instances with methods.
- **Transferables:** Large binary data (ArrayBuffer, ImageBitmap, OffscreenCanvas) can be transferred instead of copied — zero-copy transfer with O(1) time regardless of size. worker.postMessage(buffer, [buffer]) — the second argument lists transferable objects. After transfer, the original is neutered (zero-length).
- **SharedArrayBuffer:** Allows shared memory between threads. const shared = new SharedArrayBuffer(1024). Both threads access the same memory — requires Atomics API for synchronization to prevent race conditions. Requires cross-origin isolation headers (COOP/COEP) for security reasons.
- **Worker patterns:** Dedicated workers (one-to-one), shared workers (multiple tabs share one worker), service workers (network proxy, separate concept).
- **Comlink:** A library that wraps Workers in a Proxy, making cross-thread function calls look like regular async function calls — eliminating the manual postMessage/onmessage boilerplate.

**Real-world example:** Figma uses Web Workers extensively for their vector graphics engine. Rendering complex design files — computing bezier curves, applying effects, and calculating layout for thousands of elements — would freeze the UI on the main thread. Figma runs their rendering engine entirely in a Web Worker, posting canvas drawing commands back to the main thread via OffscreenCanvas transferables. This architecture allows Figma to render at 60fps during design manipulation that would take seconds on a naive main-thread implementation.

**Key takeaway:** Move any operation that takes >16ms (one frame at 60fps) to a Web Worker to preserve UI responsiveness. Prime candidates: JSON parsing of large payloads, image/video processing, cryptographic operations, data aggregation of large datasets, WebAssembly computation. The message-passing overhead (structured clone) is negligible compared to the benefit of not blocking renders.` },
    { id: 43, name: "Service Workers", desc: `Service Workers are JavaScript scripts that run in a background thread and act as a network proxy between the browser and servers — intercepting, caching, and modifying network requests and responses. They are the enabling technology for Progressive Web Apps (PWAs): offline functionality, push notifications, background sync, and installable web apps all run on Service Workers. Unlike Web Workers, Service Workers have a specific lifecycle tied to browser registration and persist between page loads.

**How it works:**
- **Registration:** navigator.serviceWorker.register('/sw.js') registers the Service Worker. The browser downloads and installs it in the background. Service Workers scope to a path: registering at /app/ intercepts only requests from /app/ and below.
- **Lifecycle:** install event — the SW is installed; cache static assets here. activate event — the old SW is replaced; clean up old caches here. fetch event — every network request from the controlled page triggers this; the SW can respond from cache, fetch from network, or modify the request.
- **Caching strategies:** Cache-first (serve from cache; network only for misses — fast but stale), Network-first (try network; fall back to cache — fresh but offline-capable), Stale-while-revalidate (serve cache immediately, update cache in background — fast and eventually fresh), Cache-only, Network-only.
- **Workbox:** Google's library that abstracts Service Worker caching strategies into declarative configuration. Workbox.routing.registerRoute(/\.js$/, new CacheFirst()) routes JS requests through cache-first. Precaching statically assets during install. Used by most production PWA implementations.
- **Fetch interception:** self.addEventListener('fetch', e => { if (e.request.url.includes('/api/')) { e.respondWith(networkFirst(e.request)) } else { e.respondWith(cacheFirst(e.request)) } }). Different strategies for different resource types.
- **Push notifications:** Service Workers receive push events from a push server even when the page is closed. self.addEventListener('push', e => self.registration.showNotification(e.data.text())) — push notifications work without the app being open.
- **Background sync:** Register sync events that fire when connectivity is restored. User submits a form offline; SW queues the request; when network returns, SW fires the sync event and sends the queued data.
- **HTTPS requirement:** Service Workers require HTTPS (except localhost) — they can intercept all network traffic, so the browser enforces a secure origin constraint.

**Real-world example:** Twitter Lite (Twitter's PWA) uses Service Workers to cache the application shell (HTML, CSS, JS) and recent timeline data. Users on slow 3G connections in emerging markets see the cached timeline instantly (<200ms) while the Service Worker fetches fresh tweets in the background. Twitter reported that switching to a Service Worker-cached PWA reduced load time by 30% and increased pages per session by 65% for users on slow connections — the offline-capable experience was the primary driver of their PWA adoption strategy.

**Key takeaway:** Implement Service Workers for any web app where users expect native-like performance — especially on mobile. Start with Workbox and precache your app shell (HTML, CSS, critical JS). Add runtime caching for API responses using stale-while-revalidate. The 20-minute investment to add a basic Service Worker delivers measurable improvements to load performance and perceived reliability for all users, not just offline scenarios.` },
  ],
};
export default javascriptCore;
