const performance = {
  name: "Performance",
  icon: "⊞",
  color: "#22C55E",
  concepts: [
    { id: 81, name: "Core Web Vitals", desc: `Core Web Vitals are Google's three field metrics that measure real user experience — loading performance, interactivity, and visual stability. Introduced in 2020 and incorporated into Google Search ranking in 2021, they create a direct feedback loop between user experience quality and search visibility. Unlike synthetic lab metrics (Lighthouse scores), Core Web Vitals are measured on real user devices in real network conditions via the Chrome User Experience Report (CrUX), making them the most honest signal of how your site actually feels to users.

**How it works:**
- **LCP (Largest Contentful Paint) — target: < 2.5s:** Measures when the largest visible content element (typically a hero image, heading, or video thumbnail) finishes rendering. Represents perceived load speed — the moment users feel "the page is loaded." The LCP element is determined at runtime; it's usually the above-the-fold image or the h1. Optimise by: preloading the LCP image (fetchpriority="high"), eliminating render-blocking resources, using a CDN, and ensuring the server responds quickly (TTFB < 600ms).
- **INP (Interaction to Next Paint) — target: < 200ms:** Replaced FID in March 2024. Measures the worst-case interaction delay across the entire page visit — the time from user input (click, keypress, tap) to the next frame painted. Reflects responsiveness throughout the session, not just on load. Optimise by: breaking up long tasks (> 50ms on the main thread), using scheduler.yield() or setTimeout to yield to the browser between chunks, avoiding synchronous work in event handlers.
- **CLS (Cumulative Layout Shift) — target: < 0.1:** Measures unexpected layout shifts — elements moving without user interaction. Caused by: images without explicit width/height (browser doesn't know size until loaded), dynamically injected content above existing content, web fonts swapping in with different metrics. Optimise by: always set width and height on images/video, reserve space for ads and dynamic content (min-height), use font-display: optional or preload fonts.
- **Measuring:** Google Search Console (field data, 28-day rolling window), PageSpeed Insights (combines field CrUX data with lab Lighthouse data), web-vitals npm library for real-user monitoring, Chrome DevTools Performance panel for debugging specific issues.
- **The 75th percentile rule:** Google evaluates sites at the 75th percentile of page visits — you need 75% of your real users to experience good scores, not just your average user. P75 is significantly harder than median; it means your worst-quarter experience must still be good.

**Real-world example:** The Financial Times improved their LCP from 4.5s to 2.1s by preloading article hero images and optimising their server response time. They tracked the change against their "Scroll Depth" engagement metric and found that improving LCP by 1 second correlated with a 7% increase in article completion rates — directly validating Google's claim that Core Web Vitals correlate with business outcomes. Their engineering team now measures Core Web Vitals in CI/CD and blocks deploys that regress P75 scores.

**Key takeaway:** Measure field data (CrUX via PageSpeed Insights or Search Console), not just Lighthouse lab scores — your development machine on a fast network is not representative. Focus on P75, not averages. LCP is the highest-leverage metric for most sites: optimise the LCP element with fetchpriority="high" and eliminate render-blocking scripts. INP is the newest and often most neglected — profile main thread work during interactions using Chrome's Performance panel.` },
    { id: 82, name: "Code Splitting", desc: `Code splitting is the practice of dividing a JavaScript bundle into smaller chunks that are loaded on demand rather than all at once on page load. The problem it solves: a monolithic bundle forces users to download all application code before the page becomes interactive — code for settings pages, admin panels, and rarely-used features loaded on every visit. Code splitting ensures users download only the code needed for the current page, dramatically reducing Time to Interactive for initial loads.

**How it works:**
- **Dynamic import():** The fundamental primitive. import('./HeavyComponent') returns a Promise that resolves to the module when loaded. Bundlers (Vite, webpack, Rollup) automatically create a separate chunk for dynamically imported modules. const Chart = await import('./Chart') triggers a network request only when that line executes.
- **React.lazy() + Suspense:** const Chart = React.lazy(() => import('./Chart')). Render inside <Suspense fallback={<Spinner />}>. React shows the fallback while the chunk loads, then renders the component. Route-level lazy loading: const Settings = React.lazy(() => import('./pages/Settings')), used in <Route> — each route becomes a separate chunk.
- **Route-based splitting (automatic):** Next.js, Vite with React Router, and most meta-frameworks automatically split bundles per route. Each page's JavaScript is a separate chunk, loaded only when that route is visited. This is the highest-leverage code splitting strategy — zero configuration required, immediate impact on initial bundle size.
- **Component-level splitting:** Split heavy components that are not needed immediately: date pickers, rich text editors, chart libraries, map components. These often import large dependencies (moment.js, Chart.js, Leaflet) that shouldn't be in the main bundle. Conditionally render with Suspense only when needed.
- **Vendor chunk splitting:** Separate vendor code (node_modules) from application code — vendor code changes less frequently than application code, so users cache it longer. Vite does this automatically; webpack requires SplitChunksPlugin configuration. manualChunks in vite.config.js groups specific libraries into named chunks (react-vendor, ui-vendor, etc.).

**Real-world example:** Airbnb's search page ships ~800KB of JavaScript total, but only ~180KB is loaded for the initial search results page. Listing details, booking flow, host dashboard, and account settings are separate chunks loaded on demand. Their engineering team measured that reducing the initial bundle from ~400KB to ~180KB improved Time to Interactive by 1.8 seconds on median mobile hardware — directly increasing search-to-booking conversion rates. They enforce per-route bundle size budgets in CI to prevent regression.

**Key takeaway:** Route-based code splitting (automatic in Next.js, trivial in React Router v6 with lazy()) is non-negotiable for any application with more than 3–4 pages. Component-level splitting for heavy UI components (editors, charts, maps) provides the next tier of improvement. Use the browser's Network tab to verify chunks are loading lazily — watch for unnecessary eagerly-loaded chunks. Measure the real impact with Lighthouse or WebPageTest before and after; code splitting is one of the highest-ROI performance optimisations available.` },
    { id: 83, name: "Lazy Loading", desc: `Lazy loading is the strategy of deferring the loading of non-critical resources — images, components, scripts, fonts, data — until they are actually needed. The browser's default behaviour is eager: it processes every resource it encounters, regardless of whether the user will ever reach that part of the page. Lazy loading inverts this: load what's needed now, defer everything else. For image-heavy pages and large JavaScript applications, this is often the single biggest performance win available.

**How it works:**
- **Native image lazy loading:** <img loading="lazy" src="photo.jpg" alt="...">. The browser defers fetching the image until it's within a threshold distance of the viewport (typically 1–2 screen heights below). Supported natively in all modern browsers since 2019. Zero JavaScript required. Critical: never use loading="lazy" on above-the-fold images (they should load immediately); use it for anything below the fold.
- **IntersectionObserver API:** The browser-native API for detecting when elements enter the viewport. Used to implement custom lazy loading: const observer = new IntersectionObserver((entries) => { if (entry.isIntersecting) { loadContent(); observer.unobserve(entry.target); } }). Powers Astro's client:visible, React's react-lazyload, and most lazy loading libraries.
- **React.lazy() + Suspense:** const Modal = React.lazy(() => import('./Modal')). The component code is not downloaded until Modal is first rendered. Wrap in <Suspense fallback={<div>Loading...</div>}> to show a placeholder while loading. Combine with conditional rendering: only render Modal when isOpen is true — the chunk loads on first open, then is cached.
- **Data lazy loading:** Don't fetch all data on page load. Fetch above-the-fold data immediately; defer below-the-fold data until the user scrolls. Infinite scroll and pagination are forms of data lazy loading. TanStack Query's prefetchQuery and React's useTransition allow pre-fetching data when user intent is detected (hover over a link).
- **Preload vs lazy load:** These are complements. Preload critical resources (LCP image, critical font) to load them faster than the browser would discover them. Lazy load non-critical resources to avoid loading them at all until needed. The combination — preloading critical resources and lazy loading everything else — defines the optimal loading strategy.

**Real-world example:** Pinterest's image-heavy feeds use lazy loading with blur-up placeholders: when a user scrolls into a new grid section, a tiny blurred placeholder image (LQIP — Low Quality Image Placeholder, ~500 bytes base64-encoded) is shown immediately, while the full-resolution image loads in the background. When loaded, it transitions from blurred to sharp. Pinterest reports this technique reduced perceived load time by 40% for their grid pages — users see content immediately (the blurred placeholder) rather than empty space, which measurably reduces bounce rate.

**Key takeaway:** Add loading="lazy" to every below-the-fold image in your application — it takes 10 seconds and has zero downside for supporting browsers. Use React.lazy() for every heavy component that isn't needed on initial render (modals, drawers, non-default tabs, admin panels). Never lazy load above-the-fold content — it makes the page feel slow. The LCP element should always load eagerly with fetchpriority="high". Audit your page with Chrome DevTools Network tab filtered to "Img" — any image loaded before the user would see it is a candidate for lazy loading.` },
    { id: 84, name: "Tree Shaking", desc: `Tree shaking is a form of dead code elimination performed by JavaScript bundlers — it analyses which exports from your modules are actually imported and used, and removes the rest. The name comes from the metaphor of shaking a tree to make dead leaves fall. In a world where npm packages contain hundreds of utilities but you use three, tree shaking is the mechanism that ensures you only ship those three to your users. It requires ES module syntax (import/export) — the static structure that allows bundlers to determine at build time what's used without executing code.

**How it works:**
- **ES modules requirement:** Tree shaking only works with ES module syntax (import { specific } from 'lib'), not CommonJS (const { specific } = require('lib')). CommonJS imports are dynamic — the bundler can't know at build time what properties will be accessed. This is why lodash-es (ES module version) tree-shakes while lodash (CommonJS) does not: import { debounce } from 'lodash-es' ships only debounce's code.
- **Static analysis:** Bundlers (Rollup, esbuild, Vite, webpack 5) perform static analysis of the module graph. They trace: what is exported from each module, what is imported by each consumer, and mark unused exports as "dead code." During minification, dead code is eliminated. Rollup pioneered tree shaking; esbuild performs it ~100× faster due to Go implementation.
- **Side effects:** Code with side effects (module-level statements that execute on import) cannot be tree-shaken even if no exports are used — the bundler must execute it. package.json "sideEffects": false signals that a package has no side effects and all unused code can be eliminated. "sideEffects": ["./src/polyfills.js"] whitelists specific files with side effects.
- **Barrel files (re-export problem):** A barrel file (index.js that re-exports from many files) can defeat tree shaking in some bundlers. import { Button } from '@company/ui' where ui/index.js re-exports everything may cause the entire library to be bundled if the bundler can't trace through re-exports. Solution: deep imports (import Button from '@company/ui/Button') or ensure the library's package.json has "sideEffects": false.
- **Verifying tree shaking:** Bundle analyser (vite-bundle-visualiser, webpack-bundle-analyzer) shows what's in your bundle. Bundlephobia.com shows the bundle cost of any npm package. Import cost VS Code extension shows inline bundle size for each import.

**Real-world example:** Moment.js is the canonical tree-shaking failure: its 232KB minified bundle loads all 160+ locale files even when you only use English, because Moment uses CommonJS and dynamic requires. Date-fns (ES modules, tree-shakeable) ships only the functions you import. A project switching from import moment from 'moment' to import { format, parseISO } from 'date-fns' typically reduces date-related bundle size from 232KB to ~8KB — a 97% reduction. This single change improved First Contentful Paint by ~500ms on mobile 4G for many applications.

**Key takeaway:** Import specifically, not wholesale: import { useState } from 'react', not import React from 'react' then React.useState. Choose tree-shakeable alternatives to large monolithic libraries: date-fns over moment, lodash-es over lodash. Verify your imports tree-shake using the bundle analyser — "I think it's tree-shaken" is not the same as "I verified it's tree-shaken." Set "sideEffects": false in your own library's package.json to enable consumers to tree-shake it.` },
    { id: 85, name: "Bundle Analysis", desc: `Bundle analysis is the practice of examining the contents of your JavaScript bundles to understand what's inside them, why it's there, and whether it should be. Bundles grow silently — a library added for a small feature, a transitive dependency pulled in by an update, a barrel import that accidentally includes an entire design system. Without regular analysis, bundles accumulate weight invisibly until a performance audit reveals that users are downloading 2MB of JavaScript they don't need. Bundle analysis makes the invisible visible.

**How it works:**
- **Vite bundle visualiser:** npx vite-bundle-visualizer (or rollup-plugin-visualizer) generates an interactive treemap showing each module's contribution to the bundle by size. Installed as a plugin in vite.config.js, it runs during build and opens a visualisation in the browser. Each rectangle represents a module; size represents gzipped or uncompressed bytes. Hover to see exact sizes; click to explore dependency trees.
- **webpack-bundle-analyzer:** The original bundle visualiser for webpack projects. Generates a zoomable treemap from the webpack stats file. webpack --profile --json > stats.json, then webpack-bundle-analyzer stats.json. Shows all chunks and their contents. Essential for large webpack applications.
- **source-map-explorer:** Analyses source maps (not the bundle directly) to show the original source contribution per bundle byte. npm install -g source-map-explorer, then source-map-explorer bundle.js bundle.js.map. More accurate than treemap visualisers for understanding true pre-minification source contributions.
- **Bundlephobia.com:** Enter any npm package name to see its minified + gzipped size, bundle cost, and download time. Shows the cost before you install — a critical habit before adding any dependency. Also shows if a package is tree-shakeable and suggests lighter alternatives.
- **Import Cost VS Code extension:** Displays the bundle size of each import inline as you type in VS Code: import { useState } from 'react' // 2.5KB. Provides immediate feedback about import cost while writing code, rather than discovering it at bundle analysis time.

**Real-world example:** Sentry (error monitoring SaaS) audited their JavaScript SDK in 2021 and found it had grown to 87KB gzipped — too large to recommend including on all pages. Using bundle analysis, they identified that the entire OpenTelemetry tracing library was included as a dependency but only used for one optional feature. By making it dynamically imported and tree-shaking the rest, they reduced the core SDK from 87KB to 26KB gzipped. The reduction was discovered through bundle analysis that revealed one dependency was 61KB of the 87KB total.

**Key takeaway:** Run bundle analysis before every major dependency addition and after every dependency upgrade — upgrades frequently include new transitive dependencies. Establish size budgets (e.g., main bundle < 100KB gzipped, per-route chunks < 50KB) and automate checks in CI (bundlesize, size-limit npm packages). The treemap visualisation often reveals surprises: polyfills included for already-supported browsers, duplicate libraries (two different date libraries), and large dependencies included for small utility functions.` },
    { id: 86, name: "Image Optimization", desc: `Images are typically the largest contributors to page weight — a single unoptimised hero image can be 3–5MB while an optimised equivalent is 150–300KB. Image optimisation is the highest-ROI performance improvement for most content and marketing sites: it requires no code refactoring, directly reduces LCP, and often cuts page weight by 60–80%. The combination of modern formats (AVIF, WebP), correct sizing, lazy loading, and CDN delivery is the complete image optimisation stack.

**How it works:**
- **Modern formats:** AVIF offers 50% smaller files than JPEG at equivalent visual quality; WebP offers 25–35% smaller files. Use <picture> with format fallbacks: <picture><source srcset="img.avif" type="image/avif"><source srcset="img.webp" type="image/webp"><img src="img.jpg" alt="..."></picture>. Browsers request the first format they support; older browsers fall back to JPEG. CDNs (Cloudflare, Cloudinary, Imgix) auto-convert to AVIF/WebP based on Accept headers.
- **Responsive images (srcset + sizes):** Never serve a 1200px image to a 375px mobile screen. <img srcset="img-400.jpg 400w, img-800.jpg 800w, img-1200.jpg 1200w" sizes="(max-width: 600px) 100vw, 50vw" src="img-800.jpg">. The browser selects the appropriate size based on viewport width and device pixel ratio. A 400px image on a 2x display needs 800px of pixels — size accordingly.
- **Compression and quality:** JPEG quality 80–85 is visually indistinguishable from quality 95–100 at 40–50% smaller size. Use imagemin, sharp, or Squoosh for batch compression. Progressive JPEGs load top-to-bottom blur that sharpens, which feels faster than top-to-bottom scan. For photographic images, AVIF at quality 65–75 rivals JPEG quality 85 in visual fidelity.
- **Next.js <Image> component:** Handles format conversion (AVIF/WebP), responsive srcset generation, lazy loading, blur placeholder, CLS prevention (reserves space before image loads), and CDN delivery automatically. Replaces manual optimisation for Next.js apps. Requires explicit width and height props, which forces space reservation and eliminates CLS.
- **LCP optimisation:** The LCP image (hero, above-the-fold) must be preloaded: <link rel="preload" as="image" href="hero.jpg" fetchpriority="high">. Never lazy-load the LCP image. Use fetchpriority="high" on the <img> tag itself. Ensure the image is served from a CDN close to users. These steps together can cut LCP by 1–2 seconds.

**Real-world example:** Unsplash serves over 2 billion image requests monthly. Their image delivery pipeline: original images uploaded as high-resolution TIFFs → processed by an image pipeline that generates AVIF, WebP, and JPEG variants at multiple sizes → served via Cloudflare CDN with automatic format selection based on browser Accept headers → lazy-loaded in the grid with LQIP (low-quality image placeholder) blur-up effect. The result: a 6MB TIFF becomes a 45KB AVIF delivered to a modern browser on a mobile device. Unsplash estimates this pipeline reduces their bandwidth costs by ~70% versus serving original files.

**Key takeaway:** Every image on your site should be: correct format (AVIF/WebP with JPEG fallback), correctly sized (srcset for responsive), lazy-loaded below the fold (loading="lazy"), and served from a CDN. The LCP image should be preloaded (fetchpriority="high", no lazy loading). If you're on Next.js, use <Image> — it handles all of this automatically. Audit images in Chrome DevTools: "Images" in the Network tab filtered by size reveals quick wins. An image > 200KB on a content page is almost always an optimisation opportunity.` },
    { id: 87, name: "Font Optimization", desc: `Web fonts are a hidden performance cost — they block text rendering, cause layout shifts when they swap in, and add 100–500KB of download weight per family. Typography is essential to design identity, but unoptimised font loading is one of the most common causes of poor CLS and LCP scores. The good news: font optimisation has well-established techniques that can cut font payload by 70%+ and eliminate font-caused layout shifts.

**How it works:**
- **font-display descriptor:** Controls how the browser handles the font loading period. font-display: block — text is invisible during loading (FOIT — Flash of Invisible Text). font-display: swap — shows fallback font immediately, swaps when loaded (FOUT — Flash of Unstyled Text, can cause CLS). font-display: optional — uses the font only if already cached; otherwise uses fallback permanently on this page visit (best for performance, no CLS). font-display: fallback — short invisible period, then fallback, then swap if loaded quickly. For most sites: font-display: optional for body text, font-display: swap + size-adjust for headings.
- **Preloading critical fonts:** <link rel="preload" as="font" href="/fonts/Inter.woff2" crossorigin> in <head> tells the browser to fetch the font at high priority, before it encounters the @font-face rule. Reduces FOUT duration. Only preload fonts used above the fold — preloading all fonts defeats the purpose.
- **Subsetting:** A full Latin character set in a font may be 300KB. The characters actually used on your site may represent 20KB. Font subsetting extracts only the glyphs needed. unicode-range in @font-face defines which character ranges this font file covers — browsers only download font files whose character range intersects the page's content. Google Fonts uses unicode-range subsetting automatically. For self-hosted fonts, use glyphhanger or pyftsubset.
- **Variable fonts:** A single variable font file replaces multiple weight/style files (regular, bold, italic, bold-italic). One .woff2 file (typically 50–100KB) versus four separate files (4 × 30–60KB = 120–240KB). CSS uses font-variation-settings or standard font-weight with arbitrary values: font-weight: 350 works with a variable font.
- **System font stack:** The ultimate font optimisation — use no web font at all. font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif renders in the OS's native font (San Francisco on Apple, Segoe UI on Windows, Roboto on Android). Zero download, zero layout shift, native-feeling typography. GitHub uses this for their UI; many high-performance sites adopt it for body text.

**Real-world example:** The Guardian newspaper reduced their web font payload from 430KB to 95KB by: subsetting to only the Latin characters used in English journalism, using variable fonts (one file for all weights), setting font-display: optional for body text (system fallback on slow connections, web font on fast ones), and size-adjust to make the fallback font metrics match the web font metrics (eliminating layout shift during swap). The combined effect reduced their CLS score from 0.18 to 0.04 — from "Needs Improvement" to "Good" on Core Web Vitals.

**Key takeaway:** Font-display: optional is the highest-performance choice for body text — if your font loads quickly (cached or fast connection), great; if not, users see the system font without any layout shift. Always preload your primary heading font. Use variable fonts — they replace multiple files with one. Measure font impact by loading your page with fonts blocked (in DevTools, block the font URL) and comparing LCP and CLS scores. If self-hosting fonts (recommended for privacy and latency), add font-display and unicode-range to your @font-face declarations.` },
    { id: 88, name: "Memoization (useMemo / useCallback)", desc: `Memoization in React means caching the result of a computation or a function reference between renders so that it is only recomputed when its dependencies change. useMemo caches a computed value; useCallback caches a function identity. Both solve a specific problem: React components re-render frequently, and some work done during render is expensive enough that repeating it on every render is wasteful. However, memoization is widely overused — it adds code complexity and has its own overhead, so profiling before applying it is non-negotiable.

**How it works:**
- **useMemo:** const sortedItems = useMemo(() => items.sort(compareFn), [items]). The sort runs once when items changes, then returns the cached result on subsequent renders. React stores the last input (items) and output (sorted array). If items is the same reference, the cached result is returned without re-running the sort. Use when: the computation is measurably expensive (O(n log n) sort of large arrays, regex operations, complex data transforms), and the component re-renders frequently for other reasons.
- **useCallback:** const handleClick = useCallback((id) => { onSelect(id); }, [onSelect]). Returns the same function reference across renders when dependencies don't change. Without useCallback, handleClick is a new function object on every render — referential inequality. Use when: the function is passed as a prop to a memoized child component (React.memo) where referential equality is required, or as a dependency in another hook's dependency array.
- **When NOT to use:** Most computations (filtering small arrays, string formatting, simple arithmetic) are microseconds and the memoization overhead (reference comparison, cache storage) is comparable. Adding useMemo to a 0.1ms computation is net negative. The React team's advice: don't memoize unless you've profiled and found a real bottleneck. New React compilers (React Forget / React Compiler) automatically apply memoization where beneficial, eliminating the need for manual useMemo/useCallback in future.
- **Dependency array correctness:** The dependency array must include every value read inside the function that can change between renders. Omitting dependencies causes stale closures (the function captures old values). The react-hooks/exhaustive-deps ESLint rule enforces correct dependency arrays. Never disable this lint rule — fix the underlying issue instead.
- **React.memo interaction:** useCallback is primarily useful in combination with React.memo. If a child is wrapped in React.memo but receives a new function reference on every parent render, memo provides no benefit — the referential inequality triggers a re-render. useCallback stabilises the function reference, making React.memo effective.

**Real-world example:** Notion's block editor re-renders frequently as users type. Without memoization, every keystroke caused each block to re-sort its children, recalculate its formatting, and regenerate its event handlers — creating measurable jank in documents with hundreds of blocks. Profiling in React DevTools revealed that block sorting was consuming 15ms per keystroke. useMemo on the sort eliminated the jank. The critical detail: they profiled first, identified the specific expensive operation, then applied the fix — rather than pre-emptively wrapping everything in useMemo.

**Key takeaway:** Profile before memoizing — open React DevTools Profiler, record a slow interaction, find components with high render times. useMemo for expensive computations (> 1ms, re-runs on frequent renders). useCallback primarily when passing functions to React.memo-wrapped children. Avoid memoizing everything "just in case" — it adds cognitive overhead and can actually slow renders down (cache comparison overhead > computation overhead for cheap operations). The React Compiler (experimental as of 2024) will make most manual memoization unnecessary.` },
    { id: 89, name: "React.memo & shouldComponentUpdate", desc: `React.memo and shouldComponentUpdate are opt-in performance optimisations that allow React to skip re-rendering a component when its props have not changed. By default, React re-renders a component every time its parent re-renders, regardless of whether the component's own props changed. For components with expensive render logic or large subtrees, unnecessary re-renders cause measurable performance degradation. React.memo (functional components) and shouldComponentUpdate / PureComponent (class components) provide referential equality checks to prevent them.

**How it works:**
- **React.memo:** const MemoizedCard = React.memo(Card). When Card's parent re-renders, React.memo compares the previous and current props using shallow equality (Object.is for each prop). If all props are shallowly equal, React skips re-rendering MemoizedCard and reuses the previous render output. If any prop differs (including a new object/array/function reference created inline), it re-renders.
- **Shallow equality caveat:** Shallow equality means reference comparison, not deep comparison. <MemoizedCard style={{ color: 'red' }} /> creates a new object on every render — even though the value is identical, React.memo sees a new reference and re-renders. Solution: define the object outside the component or use useMemo/useCallback to stabilise references.
- **Custom comparator:** React.memo(Component, (prevProps, nextProps) => prevProps.id === nextProps.id). Returns true to skip render (props are "equal"), false to re-render. Use for deep comparison or when only certain props matter for rendering. Warning: incorrect custom comparators cause bugs (stale renders showing outdated data).
- **PureComponent / shouldComponentUpdate (class components):** class Card extends React.PureComponent automatically implements shouldComponentUpdate with shallow prop and state comparison. shouldComponentUpdate(nextProps, nextState) can return false to skip render — any logic, including deep comparison. Both are legacy patterns; functional components with React.memo are preferred for new code.
- **Where memo helps most:** Components that render often (in lists, in frequently-updating parent trees), with props that are stable (primitive values, stable object references), and with expensive render logic (complex calculations, large JSX trees). Where it doesn't help: components with unstable props (inline objects/functions), components that almost always need to re-render anyway, or cheap components where comparison overhead exceeds render overhead.

**Real-world example:** Twitter's (now X) tweet list renders thousands of tweets as users scroll. Each tweet component is wrapped in React.memo — as the user's timeline receives new tweets at the top, only the new tweet components render; existing tweet components skip re-rendering because their props (tweet data) haven't changed. Without memo, every new tweet arrival caused all visible tweets to re-render, consuming ~120ms of main thread time and causing visible jank during high-activity moments (major events, breaking news).

**Key takeaway:** Wrap components in React.memo when: (1) the component is in a list or renders many times, (2) the parent re-renders frequently for reasons unrelated to this component, and (3) the component's render is measurably expensive. Don't wrap everything in React.memo — the comparison overhead is not free. The unstable-props-defeating-memo problem is common: if you add React.memo but still pass inline objects or functions, use useMemo/useCallback to stabilise them. Always verify with React DevTools Profiler that memo is actually preventing re-renders — "I wrapped it in memo" is not the same as "it's not re-rendering."` },
    { id: 90, name: "Virtualization (Windowing)", desc: `List virtualisation (also called windowing) is the technique of rendering only the DOM nodes for items currently visible in the viewport, regardless of how many items exist in the underlying data. Rendering 10,000 list items creates 10,000 DOM nodes — the browser must layout, paint, and manage all of them in memory, causing slow initial render, janky scrolling, and high memory consumption. Virtualisation renders only ~20–50 items (whatever fits in the viewport plus a buffer), replacing off-screen items with invisible spacers that preserve scroll position. The DOM stays small; the scroll experience stays fast.

**How it works:**
- **Core mechanism:** A virtualised list calculates, based on scroll position and item height, which items are currently in the visible window plus a buffer zone above and below. It renders only those items as real DOM nodes. Items outside the window are represented by empty space (achieved by adjusting the container height and positioning rendered items absolutely or with transform). On scroll, the rendered window slides — items entering the viewport get DOM nodes, items leaving lose them.
- **Fixed vs variable height:** Fixed height items (every row 50px) are simple to virtualise — item position = index × height, visible range = Math.floor(scrollTop / height) to Math.ceil((scrollTop + viewportHeight) / height). Variable height items require storing a size cache and using ResizeObserver to measure items as they render — more complex but handled by modern libraries automatically.
- **react-window (lightweight):** FixedSizeList, VariableSizeList, FixedSizeGrid, VariableSizeGrid. Minimal API, small bundle. Best for simple flat lists and grids with known or measurable item sizes.
- **react-virtuoso (full-featured):** <Virtuoso data={items} itemContent={(index, item) => <Item item={item} />} />. Handles variable heights automatically (no need to specify height), supports sticky headers, grouping, reverse lists (for chat), incremental loading, and smooth scroll to index. The recommended choice for most applications.
- **TanStack Virtual (headless):** Framework-agnostic virtualisation primitive — works with React, Vue, Solid, Svelte. No pre-built components; provides the scroll position calculations and virtual item positions. Maximum control; requires wiring up the DOM structure manually.

**Real-world example:** Slack's message list in channels with thousands of messages uses virtualisation. Without it, loading a channel with 100,000 messages would create 100,000 DOM nodes — crashing most browsers. With virtualisation, Slack renders ~50–100 messages at any time regardless of channel history size. Jump-to-date and search navigation work by scrolling the virtual list to the target position — the browser never touches DOM nodes for off-screen messages. Slack measured that introducing virtualisation for long channels reduced memory usage by 90% and eliminated the "this channel takes forever to load" problem for high-volume Slack workspaces.

**Key takeaway:** Virtualise any list with more than 100–200 items. If your list can grow without bound (chat history, activity feed, search results), virtualise from the start — retrofitting is harder than building it in. Use react-virtuoso for most React cases (best developer experience, handles variable heights and grouping automatically). Virtualisation requires that list items have predictable height or that heights are measured after render — floating, content-dependent heights are the main implementation challenge. Test with realistic data volumes: 10 items always works; performance problems only emerge at scale.` },
    { id: 91, name: "Debouncing & Throttling", desc: `Debouncing and throttling are two techniques for controlling how frequently a function executes in response to rapid events — scroll, resize, keypress, mouse move. Without them, an event handler firing 60–100 times per second performs expensive operations (API calls, DOM updates, complex calculations) at that same rate, overwhelming both the browser and server. Both techniques reduce call frequency, but with different semantics: debounce delays until activity stops; throttle limits to a maximum rate.

**How it works:**
- **Debounce:** Delays function execution until a specified time has passed since the last call. If the function is called again before the delay expires, the timer resets. Use case: search autocomplete — you want to fetch suggestions only after the user stops typing, not on every keystroke. Implementation: function debounce(fn, delay) { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), delay); }; }. Typical delay: 300–500ms for search, 100–200ms for window resize handlers.
- **Throttle:** Ensures a function executes at most once per interval, regardless of how many times it's called. The first call executes immediately; subsequent calls within the interval are ignored (leading edge throttle) or deferred to the interval end (trailing edge). Use case: scroll event handlers — update progress indicator at most 10 times per second, not 60+ times. Typical interval: 16ms (matches 60fps), 100ms, or 250ms depending on use case.
- **React hooks pattern:** function useDebounce(value, delay) { const [debouncedValue, setDebouncedValue] = useState(value); useEffect(() => { const handler = setTimeout(() => setDebouncedValue(value), delay); return () => clearTimeout(handler); }, [value, delay]); return debouncedValue; }. Use the debounced value as the search query trigger — the API call only fires when typing pauses.
- **lodash.debounce / lodash.throttle:** Battle-tested implementations with options for leading/trailing edge control, maxWait, and cancel/flush methods. const debouncedSearch = useMemo(() => debounce(fetchResults, 300), []). Wrap in useMemo (empty deps) to create once and persist across renders. Call debounced.cancel() on unmount to prevent stale calls after component unmounts.
- **requestAnimationFrame as throttle:** For visual updates (scroll-linked animations, element position tracking), requestAnimationFrame throttles execution to the browser's refresh rate (60fps). let ticking = false; window.addEventListener('scroll', () => { if (!ticking) { requestAnimationFrame(() => { updatePosition(); ticking = false; }); ticking = true; } }). More accurate than setInterval-based throttling for animation-linked work.

**Real-world example:** GitHub's search — searching repositories with the API — debounces the search input with a 300ms delay. Without debounce, a user typing "react hooks tutorial" (20 characters at ~100ms per keystroke) would trigger 20 API calls in 2 seconds. With 300ms debounce, only 1–3 calls fire (once typing pauses between words or at the end). GitHub's API rate limit is 60 unauthenticated requests per minute — without debounce, a single search field could exhaust the rate limit in seconds. The debounce makes the feature both faster (fewer calls means faster relevant results) and more resilient.

**Key takeaway:** Debounce: text input → API calls (search, validation, save), resize event → layout recalculation. Throttle: scroll events → position-based updates, mouse move → real-time tracking, button clicks → prevent double-submission (throttle to 1 call per second). Never add event listeners to scroll or resize without debounce or throttle — these events fire at browser refresh rate (60fps) and naive handlers cause measurable performance degradation. The useDebounce custom hook pattern is clean, testable, and reusable — implement it once and use it everywhere.` },
    { id: 92, name: "requestAnimationFrame", desc: `requestAnimationFrame (rAF) is a browser API that schedules a callback to run before the browser's next repaint — at most once per frame, synchronised with the display refresh rate (typically 60fps = every 16.7ms, or 120fps = 8.3ms on high-refresh displays). It is the correct API for any visual work: animations, scroll-linked effects, canvas drawing, and DOM measurements. Unlike setTimeout/setInterval, rAF callbacks execute at the optimal moment in the browser's rendering pipeline — after the browser has processed events but before paint — and are paused automatically when the tab is backgrounded.

**How it works:**
- **The rendering pipeline:** Each frame, the browser processes: JavaScript → Style → Layout → Paint → Composite. A rAF callback runs at the beginning of this pipeline (after JavaScript event handlers, before style recalculation). This is the ideal moment to read DOM measurements (accurate, no forced layout) and queue DOM mutations (applied in the upcoming layout phase without triggering forced reflows).
- **Animation loop pattern:** function animate(timestamp) { const elapsed = timestamp - startTime; element.style.transform = \`translateX(\${easing(elapsed / duration) * distance}px)\`; if (elapsed < duration) requestAnimationFrame(animate); } requestAnimationFrame(animate). Each call schedules the next frame — the loop runs at the display's refresh rate without blocking the main thread.
- **Avoiding layout thrashing:** Reading DOM properties (offsetWidth, getBoundingClientRect) after writing them forces the browser to recalculate layout synchronously — layout thrashing. rAF separates reads and writes: read measurements first, store them, then write all DOM changes in the same frame. This batches layout recalculation to once per frame instead of once per read-write cycle.
- **CSS animations vs rAF:** CSS animations and transitions (transform, opacity) run on the compositor thread — off the main thread entirely — and can animate at full frame rate even when the main thread is busy with JavaScript. Use CSS animations for simple, self-contained animations. Use rAF + JavaScript for: animations that depend on JavaScript values (scroll position, mouse position, physics), canvas 2D/WebGL rendering, and game loops.
- **cancelAnimationFrame:** const id = requestAnimationFrame(callback); cancelAnimationFrame(id). Cancel pending rAF callbacks when a component unmounts (React cleanup in useEffect) to prevent memory leaks and state updates on unmounted components.

**Real-world example:** Framer Motion, the most popular React animation library, uses requestAnimationFrame as its rendering engine. Every animated value subscribes to the rAF loop — when any animated value is updating, Framer schedules a rAF, reads the current interpolated value, writes the computed transform to the DOM element's style, and schedules the next frame if animation continues. This produces 60fps animations synchronized with the browser's repaint schedule, independent of React's render cycle — animation performance is not affected by React component re-renders happening simultaneously.

**Key takeaway:** Use rAF for any visual work that needs to be synchronised with the display — animations, scroll-linked effects, canvas rendering. Never use setTimeout(fn, 0) or setInterval(fn, 16) for animations — they drift out of sync with the display and cause jank. For simple CSS property animations (opacity, transform), prefer CSS transitions/animations — they run off the main thread and are immune to JavaScript jank. Always cancel rAF callbacks on component unmount (return () => cancelAnimationFrame(id) in useEffect cleanup).` },
    { id: 93, name: "Resource Hints", desc: `Resource hints are HTML link elements and HTTP headers that allow developers to inform the browser about resources it will need — before the browser would discover them on its own. The browser's preloader scans HTML for resources to fetch, but it can't anticipate dynamic imports, fonts referenced in CSS, or the next page's assets. Resource hints close this gap: they let you prioritise critical resources (preload), speculatively fetch likely-needed resources (prefetch), and pre-establish connections to external origins (preconnect). Used correctly, they cut significant latency from the critical path.

**How it works:**
- **preload (<link rel="preload">):** Fetches a resource at high priority immediately, before the browser would normally discover it. Use for: the LCP image (fetchpriority="high"), critical fonts, above-the-fold CSS loaded via JavaScript, and any resource needed within 2–3 seconds of page load. <link rel="preload" as="font" href="/Inter.woff2" crossorigin> — the as attribute is required (tells the browser the resource type and priority). Warning: unused preloads waste bandwidth and trigger browser warnings.
- **prefetch (<link rel="prefetch">):** Fetches a resource at idle priority to cache it for future navigation. Use for: the next page's JavaScript bundle when intent is predictable (hovering over a nav link), resources needed after a user action, and adjacent pages in a flow (step 2 of a checkout after step 1 loads). <link rel="prefetch" href="/checkout/chunk.js"> — browser fetches during idle time, stores in cache. On navigation to the prefetched page, the resource loads instantly from cache.
- **preconnect (<link rel="preconnect">):** Establishes a TCP connection, TLS handshake, and HTTP/2 negotiation to an external origin before any request is made to it. Eliminates 150–300ms of connection setup time when the first request to that origin fires. Use for: CDNs (your image CDN, font CDN), third-party APIs (analytics, A/B testing), and any cross-origin resource used early in the page. <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>.
- **dns-prefetch (<link rel="dns-prefetch">):** Resolves DNS for a domain before it's needed — faster than preconnect but only handles DNS (not TCP or TLS). Use for third-party domains that will be needed but not immediately. Fallback for browsers that don't support preconnect.
- **fetchpriority attribute:** <img fetchpriority="high"> or <script fetchpriority="low"> — directly tells the browser's priority queue where to rank a resource. High for the LCP image, low for below-the-fold scripts. Complements preload by controlling priority without changing discovery timing.

**Real-world example:** Google Fonts instructions include two preconnect hints: <link rel="preconnect" href="https://fonts.googleapis.com"> and <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>. Without preconnect, the first CSS request to fonts.googleapis.com triggers DNS lookup (20–100ms), TCP connection (30–150ms), and TLS handshake (30–150ms) — potentially 300ms before the CSS is even requested. With preconnect, this connection is established during page load, before the browser processes the @import statement — cutting font-caused latency by 200–300ms on first load.

**Key takeaway:** Add preconnect to every external origin used in the first 5 seconds of page load (fonts, CDNs, analytics). Add preload for the LCP image with fetchpriority="high" — this is the single highest-ROI resource hint. Use prefetch on hover/touch-start for navigation links — prefetch the next page's bundle when users show intent to navigate, not all at once. Avoid over-preloading — unused preloads consume bandwidth and generate console warnings. Audit with Chrome DevTools Network tab: resources loaded late that were needed early are preload candidates.` },
    { id: 94, name: "Critical Rendering Path", desc: `The Critical Rendering Path (CRP) is the sequence of steps a browser must complete before it can display the first pixel of a web page: parse HTML into the DOM, parse CSS into the CSSOM, combine them into the render tree, calculate element positions (layout), and paint pixels to the screen. Understanding each step — and what blocks it — is the foundation of frontend performance optimisation. Every millisecond saved on the CRP directly improves First Contentful Paint and LCP.

**How it works:**
- **HTML parsing and DOM construction:** The browser parses HTML incrementally, building the DOM tree. Parsing is blocked by: synchronous <script> tags (the parser stops, waits for the script to download and execute, then continues). Non-blocking scripts: <script defer> (downloads in parallel, executes after HTML parsed), <script async> (downloads in parallel, executes immediately when ready — blocks parsing briefly). CSS does not block HTML parsing but blocks rendering (next step).
- **CSS parsing and CSSOM:** CSS stylesheets block rendering — the browser won't paint anything until all CSS is parsed. This prevents the Flash of Unstyled Content (FOUC). The CSSOM (CSS Object Model) mirrors the DOM but for style rules. Large CSS files, @import rules (which trigger additional requests), and render-blocking third-party stylesheets delay First Contentful Paint. Inline critical CSS in <style> tags to bypass this for above-the-fold content.
- **Render tree:** Combines DOM and CSSOM. Includes only visible elements (excludes display: none, <head>, <script>). Each render tree node contains the computed style for that DOM node. Only elements in the render tree participate in layout and paint.
- **Layout (reflow):** Calculates the position and size of every element. Layout is triggered by: initial page load, DOM additions/removals, window resize, style changes that affect geometry (width, height, margin, padding, font-size). Layout is expensive — especially for large DOM trees. Forced synchronous layout (reading a layout property after a write) is the cause of most layout thrashing. Reduce DOM depth; avoid triggering layout in animation loops.
- **Paint and compositing:** Paint fills pixels — backgrounds, borders, text, shadows. Compositing assembles painted layers. Properties like opacity and transform are composited without triggering layout or paint — they run on the GPU compositor thread. This is why CSS transforms and opacity are the fastest-animating properties. Promoting elements to their own compositor layer (will-change: transform) allows them to animate without affecting the rest of the page.

**Real-world example:** BBC News measured that their page was spending 400ms blocked on a third-party analytics script loaded synchronously in the <head>. The script had to download, parse, and execute before the browser could render anything. Moving the script to defer eliminated the render-blocking, cutting their Time to First Byte-to-FCP from 1.8s to 1.1s — without changing any other code. This is the CRP in practice: one render-blocking script at the top of the page created a 700ms penalty for every user on every page load.

**Key takeaway:** Eliminate render-blocking resources in the critical path: defer all non-critical JavaScript, inline critical CSS for above-the-fold content, and use preload for critical resources. Keep the DOM shallow (avoid unnecessary nesting) and the CSS selector complexity low. Use Chrome's Performance panel to record a page load and examine the waterfall: anything before First Paint on the main thread is on the critical path and a candidate for optimisation. The compositing model (transform and opacity animate for free) is not just a tip — it's the architectural reason CSS animations outperform JavaScript-driven layout animations.` },
    { id: 95, name: "Hydration & Partial Hydration", desc: `Hydration is the process of taking server-rendered static HTML and "waking it up" — attaching JavaScript event handlers, initialising component state, and connecting the React (or Vue/Angular) component tree to the existing DOM nodes. It makes a static HTML page interactive. The problem: hydration requires downloading, parsing, and executing the entire JavaScript bundle, then traversing the entire component tree — even for components that have no interactivity. This "hydration cost" grows with application size and is the primary performance bottleneck for large SSR applications.

**How it works:**
- **Full hydration (traditional SSR):** Server renders complete HTML → browser displays HTML immediately (fast FCP) → browser downloads JavaScript bundle → React/Vue/Angular processes the entire component tree → event handlers attached → page becomes interactive. The gap between FCP and TTI (Time to Interactive) is the hydration period — during which the page looks interactive but isn't. On slow networks with large bundles, this can be 3–8 seconds.
- **Hydration mismatch errors:** React compares the server-rendered HTML with what it would render on the client. Any difference (dynamic content, client-only APIs, timezone differences) causes a hydration mismatch — React discards the server HTML and re-renders from scratch, wasting the benefit of SSR. suppressHydrationWarning suppresses warnings for intentionally different content; useEffect defers client-only logic until after hydration.
- **Partial hydration (Islands Architecture):** Only the interactive components ("islands") are hydrated with JavaScript. Static content (text, images, non-interactive UI) is served as plain HTML with zero JavaScript. Astro's client:load, client:visible, and client:idle directives implement this. A marketing page with 95% static content and 5% interactive components (a form, a carousel) hydrates only those 5% — the JavaScript bundle shrinks by 95%.
- **Progressive hydration:** Hydrate high-priority (above-the-fold, user-interacting) components first; defer low-priority hydration. React 18's concurrent features enable this — Suspense boundaries can be hydrated in priority order based on user interaction. Clicking a button triggers that component's hydration before other components.
- **React Server Components vs hydration:** RSC is a fundamentally different model — Server Components never hydrate (they have no client-side code). Only Client Components hydrate. This shifts the question from "how to optimise hydration" to "minimise what needs hydrating" — every component kept as a Server Component is hydration that never happens.

**Real-world example:** Shopify migrated their storefront themes (used by millions of merchant storefronts) from a full SPAs to Astro with Islands Architecture. A typical product page (hero image, product details, description, reviews) needed JavaScript only for the Add to Cart button, the image carousel, and the variant selector — three islands in a sea of static content. The migration reduced JavaScript from ~280KB to ~45KB per page. Time to Interactive dropped from 3.8s to 1.2s on median mobile — directly improving conversion rates, which Shopify's data shows correlate strongly with TTI.

**Key takeaway:** Understand hydration as the cost of making SSR interactive — the HTML is free (fast FCP), but JavaScript to hydrate it is not. Minimise what needs hydrating: prefer Server Components (RSC) for data display, use Islands Architecture for content sites, apply progressive hydration with Suspense for complex apps. The hydration mismatch error is a real debugging problem — avoid client-only state initialised during SSR by checking if (typeof window !== 'undefined') or deferring to useEffect. Streaming SSR + Suspense is the modern solution to the hydration delay problem in React applications.` },
    { id: 96, name: "Streaming SSR", desc: `Streaming SSR is a rendering technique where the server sends HTML to the browser in chunks (a stream) as it generates them, rather than waiting until the entire page is rendered before sending anything. Traditional SSR has a waterfall: all data fetches must complete before rendering starts, then the complete HTML is sent — users see nothing until the slowest data fetch finishes. Streaming inverts this: the server sends the page shell immediately, then streams in each section as its data resolves. Users see content progressively, with fast perceived load times even when some data is slow.

**How it works:**
- **HTTP streaming:** HTTP/1.1 supports chunked transfer encoding — the server sends data in chunks with Transfer-Encoding: chunked, and the browser renders each chunk as it arrives. HTTP/2 supports this natively via streams. The browser's incremental HTML parser renders content as chunks arrive — it doesn't wait for the complete document.
- **React renderToPipeableStream:** React 18's streaming server renderer. const { pipe } = renderToPipeableStream(<App />, { onShellReady() { pipe(response); } }). The "shell" (the HTML structure that can be rendered without all data) is sent immediately. Suspense boundaries act as async split points — React renders what it has, sends it, then streams in each Suspense boundary as its data resolves.
- **Suspense boundaries as stream chunks:** Each <Suspense fallback={<Skeleton />}> boundary is a streaming chunk. React sends the fallback immediately, then sends the real content as a script that replaces the fallback when the async Server Component resolves. Users see the skeleton immediately; real content replaces it progressively. No client-side data fetching, no useEffect, no loading state management — it's all handled by the stream.
- **Next.js App Router streaming:** Automatic with async Server Components and Suspense. loading.jsx files in the App Router are Suspense fallbacks for the entire route. <Suspense> around individual slow components allows fast components to appear immediately. The Page component renders; the slow data component shows a skeleton until its fetch resolves.
- **TTFB vs FCP:** Streaming improves perceived performance but doesn't reduce Time to First Byte (TTFB) — the server still starts processing before sending anything. It improves FCP (First Contentful Paint) — users see the shell content faster — and LCP if the LCP element is in the shell. The primary benefit is eliminating the "blank page" during data fetching.

**Real-world example:** Vercel's v0 (AI code generation tool) uses streaming SSR to show the page shell — navigation, input area, previous generations — immediately on load, while the AI generation results stream in. The page renders with real content in < 200ms (the shell). AI-generated code streams in word by word. Without streaming, the user would see nothing until the AI finished generating (5–30 seconds). With streaming, they see immediate UI and content progressively — the experience is responsive from the first interaction.

**Key takeaway:** Streaming SSR is the correct rendering model for data-dependent pages in React 18+ / Next.js App Router. Identify your page's natural hierarchy: the shell (navigation, layout, non-async components) should render and stream immediately; slow data components should be wrapped in Suspense with meaningful skeletons. Avoid "Big Suspense" — wrapping the entire page in one Suspense boundary provides no streaming benefit (the whole page waits for the slowest component). Nest Suspense boundaries granularly around each independently-loading section for maximum streaming benefit.` },
  ],
};
export default performance;
