const fundamentals = {
  name: "Fundamentals",
  icon: "◆",
  color: "#F97316",
  concepts: [
    { id: 1, name: "Software Testing", desc: `Software testing is the systematic process of evaluating software to detect differences between expected and actual behaviour — finding defects before they reach users. But testing is more than bug-finding: it provides confidence, validates that requirements are met, characterises risk, and drives better design (code that is hard to test is usually hard to maintain). Every major software failure in history — from the Ariane 5 rocket explosion to the Knight Capital trading algorithm that lost $440 million in 45 minutes — traces back to inadequate testing of some form.

**How it works:**
- **The testing process:** Define objectives (what are we verifying?) → design test conditions (what scenarios matter?) → create test cases (specific steps and expected outcomes) → execute tests → compare actual vs expected results → report defects → retest after fixes. This cycle repeats throughout development and at release.
- **Static vs dynamic testing:** Static testing — examining artefacts without executing code: code reviews, inspections, static analysis (linters, SAST tools). Finds defects early and cheaply. Dynamic testing — executing the software with real inputs and observing behaviour. Required to verify runtime behaviour, integrations, and performance.
- **Manual vs automated testing:** Manual testing — a human exercises the software, observes, and judges. Essential for exploratory testing, usability, and scenarios where human judgement is required. Automated testing — scripts execute and verify test cases programmatically. Essential for regression testing, CI/CD pipelines, and any test that must run repeatedly. Neither replaces the other; both are necessary.
- **The cost of late defect detection:** A bug found in requirements costs ~1x to fix. The same bug found in design costs ~3–6x. In development: ~10x. In testing: ~15–40x. In production: ~40–1000x (plus reputational damage, data loss, and legal exposure). The exponential cost curve is why shifting testing left (earlier in the development lifecycle) is the central principle of modern software quality.
- **Testing limitations:** Testing can demonstrate the presence of bugs but never their complete absence (Dijkstra's testing principle). Exhaustive testing is impossible — a function accepting a 32-bit integer has 4 billion possible inputs. Testing strategy is always about choosing the most valuable subset of possible tests given time and resource constraints.

**Real-world example:** The Knight Capital Group incident (2012): a software deployment accidentally reactivated old dead code alongside new code, causing a trading algorithm to execute 4 million trades in 45 minutes — accumulating $7 billion in unwanted positions and a $440 million loss. The root cause was insufficient testing of the deployment process: no testing for the specific interaction between old and new code, no testing of rollback procedures, and no canary deployment that would have caught the issue on a small percentage of traffic before going fully live.

**Key takeaway:** Testing is risk management, not perfection pursuit. The question is never "have we found all bugs?" but "have we reduced risk to an acceptable level for this release?" Define your testing strategy based on: what can go wrong, how likely it is, and what the impact would be. Shift left — the earlier a defect is found, the cheaper it is to fix. Automate the repetitive, standardise the critical, and apply human judgement for the exploratory.` },
    { id: 2, name: "Verification vs Validation", desc: `Verification and validation are two distinct quality assurance activities that are frequently confused — and conflating them leads to building well-crafted software that does the wrong thing. The classic distinction, attributed to Barry Boehm: Verification asks "Are we building the product right?" Validation asks "Are we building the right product?" A system can pass all verification checks (it implements the specification correctly) while failing validation (the specification didn't reflect what users actually needed). Both are necessary; neither subsumes the other.

**How it works:**
- **Verification:** Checks that the software conforms to its specification at each stage of development. Are the requirements complete and consistent? Does the design match the requirements? Does the code implement the design? Do the tests match the specifications? Verification activities: requirements reviews, design inspections, code reviews, static analysis, unit and integration testing against specifications. Verification is about internal consistency — does each artefact correctly reflect the one above it in the development hierarchy?
- **Validation:** Checks that the final product meets the actual needs of users and stakeholders in real-world conditions. Does the system do what users actually need? Does it work in production environments? Is it usable? Validation activities: user acceptance testing (UAT), beta testing, usability studies, A/B testing, production monitoring. Validation often reveals that specifications were incomplete or incorrect — that the system was built exactly as designed, but the design was wrong.
- **The gap between them:** Specifications are imperfect models of reality. Requirements authors cannot fully anticipate how users will use software. Verification against a flawed specification produces verified but invalid software. This is why involving users throughout development (not just at the final UAT gate) and iterating with working software is the core insight of Agile — validation must happen continuously, not just at the end.
- **In practice:** Automated tests primarily verify (they check that code meets specifications encoded in test assertions). User research, usability testing, and analytics primarily validate (they check that the software meets real human needs). CI/CD automates verification; release processes include validation gates.
- **V-Model:** The V-model visualises verification and validation across development stages: requirements (validated by acceptance tests), system design (validated by system tests), detailed design (verified by integration tests), code (verified by unit tests). Each left-side activity has a corresponding right-side testing activity.

**Real-world example:** Healthcare.gov's 2013 launch failure is a textbook validation failure despite extensive verification. The system passed technical verification — it implemented the specifications, passed integration tests, and met the contractual requirements. It failed validation catastrophically: real users couldn't complete enrollment flows, the system couldn't handle production load, and the actual end-to-end user journey (from browsing to enrolled) hadn't been tested as a whole. The specifications had been verified; the user need had not been validated.

**Key takeaway:** Run both continuously, not sequentially. Don't wait for UAT to discover validation failures — involve users in requirement reviews, prototype reviews, and sprint demos throughout development. Treat production monitoring and analytics as ongoing validation — user behaviour in production is the ultimate validation test. Build automated tests to verify against specifications AND usability tests / analytics to validate against user needs.` },
    { id: 3, name: "Quality Assurance (QA) vs Quality Control (QC)", desc: `Quality Assurance and Quality Control are complementary but distinct approaches to software quality — and confusing the two (or using "QA" to mean "testing") leads to teams that detect defects reactively rather than preventing them systematically. QA is a proactive, process-focused discipline: improve the development process so fewer defects are produced. QC is a reactive, product-focused discipline: find defects that did get produced before they reach users. The highest-quality teams invest in both.

**How it works:**
- **Quality Assurance (QA) — preventing defects:** QA focuses on the processes, standards, and practices used to develop software. If defects are consistently appearing in one area, QA investigates why — is it unclear requirements? Insufficient code review? Missing design guidelines? — and improves the process. QA activities: defining coding standards and style guides, establishing code review processes, creating test strategies and templates, conducting process audits, implementing CI/CD pipelines, running retrospectives focused on defect prevention, and establishing definition-of-done criteria.
- **Quality Control (QC) — detecting defects:** QC applies to the product being built. Testing is the primary QC activity — executing software to find defects. QC activities: executing test cases, exploratory testing, reviewing test results, logging defects, performing regression tests, and sign-off decisions. QC answers "does this specific build have defects?"
- **The terminology confusion:** In most software teams, "QA engineer" refers to someone who does both QA and QC — they design test strategies (QA) and execute tests (QC). The labels are imprecise in practice. What matters is that both activities happen: process improvement and product verification.
- **Cost effectiveness:** QA (process improvement) is dramatically more cost-effective than QC (defect detection) at scale. Fixing a defect found in testing costs 10–40x more than preventing it through better requirements or design review. Toyota's manufacturing approach — "stop the line" when a defect is found and fix the root cause — applies directly to software: every production bug is an opportunity to improve the process that allowed it through.
- **Metrics:** QA metrics: defect injection rate (how many defects per feature), escaped defects (defects reaching production), code review coverage. QC metrics: defect detection rate, test coverage, defect resolution time, severity distribution.

**Real-world example:** Google's engineering productivity team exemplifies mature QA vs QC thinking. They don't just run tests (QC) — they study why tests fail (QA: flaky tests indicate process problems), why code review takes long (QA: complexity signals design issues), and why certain modules have high defect density (QA: identify areas needing architectural improvement). Their "Test Certified" program requires teams to meet process standards (QA) before their services are considered production-ready — not just pass a test suite.

**Key takeaway:** Don't settle for pure QC (finding bugs after they're written). Invest in QA activities that prevent them: clear requirements (fewer misunderstandings → fewer defects), thorough code review (catches issues before merge), definition-of-done with testing criteria, post-release retrospectives that feed back into process improvement. The ratio of effort should shift over time: mature teams spend more on QA (process) and less on QC (testing) because better processes produce fewer defects to find.` },
    { id: 4, name: "Test Plan", desc: `A test plan is a document that defines the scope, approach, resources, schedule, and objectives of a testing effort for a specific project or release. It is the contract between the testing team and stakeholders about what will and won't be tested, what "done" means, and what risks are being accepted. Without a test plan, testing is ad-hoc — coverage is inconsistent, priorities are unclear, and there is no basis for measuring completeness or making release decisions. A test plan converts testing from an art into an engineering discipline.

**How it works:**
- **Key sections of a test plan:**
- **Scope:** What features, components, and user flows are in scope for testing. Equally important: explicit out-of-scope items (third-party integrations tested in their own cycle, legacy features unchanged in this release). Scope creep in testing — like scope creep in development — is a primary cause of schedule overruns.
- **Test objectives:** What the testing effort aims to achieve. Not "find all bugs" (impossible) but specific, measurable goals: "achieve 80% branch coverage on the payment module," "verify all P0 user flows work across Chrome, Firefox, and Safari," "confirm response time under 200ms for 95th percentile under 10,000 concurrent users."
- **Resources and schedule:** Who is responsible for each testing area, test environment setup, test data preparation, and how long each phase takes. Dependencies (feature must be code-complete before integration testing begins) and milestones.
- **Entry and exit criteria:** Entry criteria define when testing can start (build is deployable, smoke tests pass, test environment is ready). Exit criteria define when testing is complete and the release is approved (all P0/P1 bugs fixed, code coverage target met, no open critical defects, stakeholder sign-off received).
- **Risk assessment:** What could go wrong? Which features have the highest defect risk? Which failures would have the highest business impact? Risk analysis drives test prioritisation — test high-risk, high-impact areas more thoroughly.
- **Living document:** A test plan should be updated as scope changes, new risks emerge, or timelines shift. A test plan that isn't maintained becomes a historical artefact rather than an operational guide.
- **Lightweight plans:** In Agile teams, a full formal test plan per sprint is impractical. Instead: a high-level test strategy document covers the project, and sprint-level test plans (or testing notes in ticket comments) cover sprint scope. The principles — scope, objectives, criteria, risks — apply at every scale.

**Real-world example:** NASA's software testing for the Mars Curiosity rover required a test plan covering: hardware-in-the-loop simulation testing, software unit and integration tests, fault injection tests (what happens when specific components fail 50 million miles from Earth?), entry-descent-landing simulation (the "7 minutes of terror"), and operator training simulations. The test plan defined which scenarios could be tested on Earth (most) and which had to be accepted as untested risks (the exact Martian soil conditions). Explicit scope and risk documentation allowed the mission team to make informed go/no-go decisions.

**Key takeaway:** Write a test plan before writing test cases — it forces explicit decisions about scope, priorities, and criteria that prevent misaligned expectations later. The most important sections are scope (what you're NOT testing is as important as what you are) and exit criteria (how you'll know when to stop). In Agile environments, lightweight test planning per feature/sprint (in the ticket or a brief test strategy note) is better than no planning, even without a formal document.` },
    { id: 5, name: "Test Case", desc: `A test case is a precise, repeatable specification for verifying one specific behaviour of a system: given this setup, when these actions are taken, the system should produce this output. It is the atomic unit of testing — the smallest thing that can independently pass or fail. Well-written test cases are the foundation of reproducible testing: any tester (or automated script) should be able to execute the same test case and reach the same conclusion. Poorly written test cases — ambiguous steps, undefined expected results, implicit preconditions — produce inconsistent results and erode trust in the testing process.

**How it works:**
- **Anatomy of a test case:**
- **ID and title:** Unique identifier and a brief, descriptive name: TC-047: User cannot checkout with an expired credit card.
- **Preconditions:** System state required before the test begins. "User is logged in," "cart contains at least one item," "test card 4000000000000002 (expired) is available." Preconditions that aren't met produce test environment failures, not product failures.
- **Test steps:** Sequential, unambiguous actions. "1. Navigate to /cart. 2. Click 'Proceed to Checkout'. 3. Enter card number 4000000000000002, expiry 01/20, CVV 123. 4. Click 'Pay Now'." Each step should be executable by a newcomer without domain knowledge.
- **Expected result:** The precise observable outcome after the last step. "The checkout fails with the message 'Your card has expired. Please use a different payment method.' The user remains on the payment page. No charge is attempted." Vague expected results ("an error appears") make pass/fail judgements subjective.
- **Actual result and status:** Recorded during execution. What actually happened vs what was expected. Pass (actual = expected) or Fail (actual ≠ expected), with the defect ID if failed.
- **Test case granularity:** One test case should verify one thing. A test case titled "User registration" that tests 15 different scenarios is hard to maintain and produces ambiguous results when it fails. Split into TC: valid registration, TC: duplicate email registration, TC: password too short, etc.
- **Positive and negative cases:** Every feature needs both: positive cases (happy path, valid inputs → success), and negative cases (invalid inputs, boundary conditions → appropriate errors). Negative cases are where most security and reliability bugs hide.

**Real-world example:** Atlassian's test case management practice for Jira — itself a project management tool — uses their own Jira for test case tracking. Each test case is a Jira issue linked to the requirement it covers. When a requirement changes, all linked test cases are flagged for review. When a test fails, a bug is automatically linked to the failing test case and the requirement it covers. This bi-directional traceability (requirement → test case → bug) creates a quality audit trail that shows exactly what was tested, when, and what was found.

**Key takeaway:** Write test cases as if someone unfamiliar with the feature will execute them — because eventually, someone will. The expected result is the most important field: if it's vague, the test is vague. Use precise, observable, measurable outcomes ("response time < 200ms," "error message reads exactly: 'Invalid email address'"). Automate test cases that run more than 2–3 times — a test case that requires manual execution for every regression cycle is technical debt waiting to compound.` },
    { id: 6, name: "Test Suite", desc: `A test suite is a collection of test cases that are grouped together for a purpose — typically because they test related functionality, run in the same environment, belong to the same test level (unit, integration, E2E), or are executed together as a logical unit. Test suites are the organisational layer above individual test cases: they allow teams to run targeted subsets of tests (all payment tests, all regression tests, all smoke tests) without running the entire test corpus. Well-organised test suites are what make a large test base manageable.

**How it works:**
- **Organisation strategies:** Feature-based (all tests for the checkout flow), module-based (all tests for the user service), priority-based (P0 critical path suite, full regression suite), test type-based (smoke suite, regression suite, performance suite), environment-based (tests that run in staging vs tests that run in production). In practice, suites use multiple dimensions — a smoke suite containing critical tests for key features, a regression suite with all stable tests, a feature suite grouping tests for a specific module.
- **Suite hierarchy:** Most test frameworks support nested suites — a top-level "E2E Tests" suite containing "Checkout Suite" containing "Payment Suite" and "Shipping Suite." This hierarchy enables targeted execution at any level of granularity: run all E2E tests, or just the payment suite, or just one test case.
- **CI/CD integration:** Different suites run at different stages of the pipeline. On every commit: unit test suite (fast, < 60 seconds). On every pull request: unit + integration suite (< 10 minutes). On merge to main: full regression suite (can take hours). Before production deploy: smoke suite on the production environment (< 5 minutes). The suite structure maps to the pipeline stage that runs it.
- **Parallelisation:** Large test suites are split across parallel workers to reduce execution time. A 2-hour regression suite running across 20 parallel workers completes in ~6 minutes. Suite organisation affects parallelisation quality — suites with many shared dependencies and state are harder to parallelise than independent, isolated test groups.
- **Maintenance:** Suites must be actively maintained. Flaky tests (those that randomly pass and fail) erode suite reliability and should be quarantined — moved to a "flaky" suite for investigation rather than left to randomly fail the main suite. Obsolete tests covering removed features should be deleted, not disabled indefinitely.

**Real-world example:** Spotify's engineering team runs test suites at three levels in their CI pipeline: a "pre-commit suite" (~200 tests, < 30 seconds) runs locally before push via a git hook; a "PR suite" (~5,000 tests, < 8 minutes) runs in CI on every pull request; a "nightly regression suite" (~50,000 tests, ~4 hours across 200 parallel workers) runs each night against the main branch. Each suite is purpose-built for its context: the pre-commit suite catches the most common mistakes instantly; the nightly suite catches subtle regressions that don't need to block PRs.

**Key takeaway:** Structure suites by both purpose and speed. Every team needs at minimum: a fast smoke suite (< 5 minutes, run on every deploy), a regression suite (complete, run before releases), and per-feature suites (targeted, run when modifying specific areas). Tag tests and run subsets by tag for flexibility (pytest's markers, Jest's --testPathPattern, Cypress's --grep). Treat suite execution time as a product metric — a regression suite that takes 4 hours discourages developers from running it, defeating its purpose.` },
    { id: 7, name: "Test Scenario", desc: `A test scenario is a high-level description of a testable situation derived from a user story, requirement, or use case — a "what to test" without the "how to test" specifics. It captures the testing intent before getting into step-by-step test case details. One scenario typically maps to multiple test cases (positive, negative, boundary). Scenarios are the bridge between requirements (what the system must do) and test cases (how to verify it) — they ensure that all meaningful testing situations are identified before detailed design begins.

**How it works:**
- **Scenario vs test case:** Test scenario: "User registers a new account." Test cases derived from it: (1) Successful registration with valid data, (2) Registration with duplicate email, (3) Registration with password below minimum length, (4) Registration with invalid email format, (5) Registration with all optional fields blank, (6) Registration with SQL injection in name field. The scenario is the abstraction; test cases are the concrete executions.
- **Deriving scenarios:** Start from user stories or requirements. For each story, ask: "What are all the distinct situations a user could be in when using this feature?" Situations = scenarios. Tools: mind maps, scenario tables, Given-When-Then structured language from BDD. The goal is completeness — no meaningful user situation should be missed.
- **Given-When-Then format:** BDD scenarios use structured language to make scenarios readable by non-technical stakeholders. Given [context/precondition], When [action], Then [expected outcome]. "Given a user is on the login page and has a valid account, When they enter correct credentials and click Login, Then they are redirected to the dashboard and a session is created." This format makes scenarios double as living documentation and executable specification.
- **Risk-based scenario selection:** Not all scenarios are equally important. Risk analysis identifies which scenarios represent the highest business risk if they fail. Checkout, payment, authentication, and data loss scenarios are typically highest risk. High-risk scenarios get the most detailed test cases; low-risk scenarios may get a single happy-path test case.
- **Scenario coverage:** Track which scenarios have test cases and which have been executed. Gaps in scenario coverage (scenarios without test cases) represent untested product behaviour — a known risk. Scenario-level tracking provides a business-readable view of test coverage that complements code coverage metrics.

**Real-world example:** Amazon's checkout process has hundreds of test scenarios: "User checks out with a saved payment method," "User checks out with a new credit card," "User applies a discount code," "User checks out when an item goes out of stock mid-session," "User checks out across multiple shipment addresses," "User in Germany checks out with EU VAT rules applied." Each scenario becomes 3–10 test cases. Amazon's test scenario library, maintained across years of e-commerce operation, captures edge cases discovered in production that are now protected by formal scenarios.

**Key takeaway:** Write scenarios before test cases — they force you to think about coverage at the right level of abstraction. Use Given-When-Then for any scenario that needs to be readable by product or business stakeholders. Aim for scenario completeness (every distinct user situation covered) before worrying about test case completeness (every step detailed). A scenario that's documented but not yet test-cased is a known gap — better than an unknown gap you discover when a bug reaches production.` },
    { id: 8, name: "Test Strategy", desc: `A test strategy is a high-level document (or section within a test plan) that defines the overall approach to testing for a project or organisation — the philosophy and framework within which all testing activity operates. While a test plan specifies the what and when for a specific release, a test strategy specifies the how and why at a level that persists across releases. It answers: what types of testing will we do, what tools will we use, how do we handle environments, what are our automation principles, and how do we make release decisions?

**How it works:**
- **Test levels and types:** The strategy defines which test levels will be used (unit, integration, system, acceptance) and which types (functional, performance, security, usability) apply to this project. It establishes the balance — what percentage of test effort goes to each level, and why. The testing pyramid (many unit tests, fewer integration tests, fewest E2E tests) is a common strategy decision encoded here.
- **Automation strategy:** What will be automated? What will remain manual? What framework (Jest, Cypress, Playwright, pytest, JUnit)? Who writes automated tests (developers, QA engineers, or both)? When are tests automated (as features are built, or as a separate QA activity)? A team without an explicit automation strategy tends toward underautomation (manual regression every release) or poor automation (brittle, unmaintained scripts).
- **Risk-based approach:** The strategy defines how risk assessment drives testing effort. High-risk areas (payment, authentication, data migration) receive proportionally more test coverage, more test types (performance and security in addition to functional), and more manual exploratory testing. Low-risk areas (static content pages, read-only reports) receive lighter coverage.
- **Environment strategy:** How many environments exist (dev, staging, production)? What data is in each? Who controls deployments to each? How are environment differences managed? Production parity (staging mirrors production as closely as possible) is a key principle — tests that pass in an environment that differs significantly from production provide false confidence.
- **Defect management process:** How are defects logged, prioritised, and tracked? What severity/priority taxonomy is used? What is the release policy for different defect severities (P0 = block release, P1 = fix before release, P2 = fix in next sprint)?

**Real-world example:** Netflix's test strategy explicitly encodes their philosophy of testing in production via chaos engineering alongside conventional pre-production testing. Their strategy document (made public via the Netflix Tech Blog) defines: automated unit and integration tests for business logic, contract tests between microservices, synthetic monitoring in production (canary transactions that verify critical flows constantly), and Chaos Monkey/ChAP for resilience validation. The strategy acknowledges that at Netflix's scale, the production environment itself is the only true test environment — so production testing is first-class, not an afterthought.

**Key takeaway:** Write a test strategy document once per project (or once per organisation for cross-project standards) and update it when the approach changes — not per release. The most important decisions to make explicit: test pyramid ratios (unit vs integration vs E2E), automation ownership (who writes and maintains tests), risk classification (what determines testing depth for a feature), and the release quality gate (what criteria must be met before shipping). Implicit strategies, followed inconsistently by different team members, produce inconsistent quality.` },
    { id: 9, name: "Test Oracle", desc: `A test oracle is any mechanism that allows a tester to determine whether a test has passed or failed — the source of truth for expected results. You cannot determine if software behaves correctly without an oracle telling you what "correct" looks like. Oracles are often implicit (testers rely on their domain knowledge or common sense), but making them explicit — documented in specifications, encoded in assertions, or captured in reference implementations — dramatically improves the consistency and reliability of testing.

**How it works:**
- **Types of oracles:**
- **Specification oracle:** Requirements documents, API contracts, design specifications. The expected result is defined in a document. Limitation: specifications can be wrong or incomplete, so testing against a flawed spec verifies the wrong thing.
- **Reference implementation oracle:** Compare output against a known-good system. Testing a new payment calculation against the legacy system that has been validated for years. Or comparing a database migration's output against the production database contents.
- **Human oracle:** A domain expert who can judge whether an output is correct. Essential for visual testing ("does this chart look right?"), complex business rule validation, and areas where specifications are incomplete. Limitation: expensive, slow, inconsistent across different people.
- **Heuristic oracle:** General principles of correct behaviour that apply broadly. "The system should never return HTTP 500 for valid inputs." "Sorting a list should never produce a list longer than the original." "Encrypting then decrypting a message should return the original." These are negative constraints, not positive specifications, but they catch large categories of bugs.
- **Statistical oracle:** For non-deterministic systems (ML models, recommendation engines, random number generators), correctness is probabilistic. "The recommendation engine should return items with > 70% relevance score on average across test users." Statistical oracles require sample-based validation rather than exact match.
- **The oracle problem:** Some systems have no reliable oracle — testing AI-generated content for "correctness," validating user experience quality, or testing novel scientific simulations. The oracle problem describes the fundamental difficulty of testing when expected results can't be definitively specified. Solutions: metamorphic testing (changing input in a known way should produce a predictably changed output, e.g., doubling a list shouldn't change the maximum value) and property-based testing.
- **Encoded in automated tests:** In automated testing, the oracle is the assertion: assert response.status == 200, assert result == expected_value. The quality of automated tests depends entirely on the quality of these oracle assertions — tests with weak or missing assertions can pass while the system produces wrong results.

**Real-world example:** Spotify's music recommendation system faces an oracle problem: there is no ground truth for "correct" recommendations. Their testing strategy uses multiple oracle types in combination: offline evaluation (A/B test against historical user listening data — did users who received these recommendations listen more?), online A/B testing (did the new algorithm increase streams vs the baseline?), and human evaluation panels (domain experts rate recommendation quality on structured scales). No single oracle is sufficient; the combination provides robust validation.

**Key takeaway:** Explicitly identify your oracle for every test before writing the test case. "What is the source of truth for the expected result?" If you can't answer this, your test is measuring something undefined. For automated tests: write strong assertions that precisely specify expected behaviour, not just "it didn't crash." Use metamorphic testing when exact oracles are unavailable — if the oracle says the output must change in a specific way when input changes in a specific way, you can test without knowing the absolute correct value.` },
    { id: 10, name: "Defect / Bug", desc: `A defect (also called a bug, fault, or failure) is a flaw in a software artefact — code, design, requirement, or configuration — that causes the system to behave differently from expected. Defects are not random; they have causes (misunderstood requirements, implementation mistakes, environment differences), and understanding those causes is how quality improves over time. Effective defect management is more than tracking bugs to closure — it is a feedback loop that drives process improvement.

**How it works:**
- **Defect lifecycle:** New → Assigned (to a developer) → Open/In Progress (developer investigating) → Fixed → Ready for Retest → Retested → Closed (if fix verified) or Reopened (if fix didn't work or caused regression). Additional states: Deferred (known issue, fixed in a later release), Won't Fix (accepted risk or not a bug), Duplicate (already reported). Each state transition should be logged with a timestamp and responsible party.
- **Writing a good bug report:** The single most important quality factor for a bug report is reproducibility. A defect report must include: steps to reproduce (precise, minimal, repeatable), expected result (what should happen), actual result (what did happen), environment (OS, browser, version, test data state), and severity/priority assessment. Screenshots, screen recordings, and log excerpts dramatically reduce time-to-fix. A report where the developer can't reproduce the defect is a report that will languish as "Cannot Reproduce" and never be fixed.
- **Defect taxonomy:** Errors cluster by cause — implementation errors (off-by-one, null pointer, incorrect business logic), integration errors (mismatched API contracts, timing issues), environment errors (works on developer machine, fails in production due to configuration), requirements errors (correctly implemented the wrong behaviour). Tracking defect cause type over time reveals systematic process failures.
- **Defect density:** Defects per lines of code or per feature point — a measure of code quality over time. New features introduced at a consistently higher defect density than old features indicate insufficient unit testing or poor code review. Tracking defect density per module identifies chronically problematic areas of the codebase that warrant refactoring or architectural changes.
- **Escaped defects:** Defects that reach production despite the testing process. Every escaped defect is a failure of the test strategy — it reached production because no test caught it. Post-mortems on escaped defects should result in a new test case that would have caught it, closing the gap.

**Real-world example:** Microsoft's Windows development team tracks "bug half-life" — the average time for a known bug to be fixed and verified. In the Windows Vista development cycle (widely criticised for quality issues), the bug half-life was notoriously long — thousands of open bugs accumulated because fix rate didn't keep up with injection rate. In response, Microsoft implemented "bug caps" per team — teams could not merge new features if their bug count exceeded their cap. This forced quality gates rather than deferring bugs to a "quality phase" at the end. Windows 7 shipped with a significantly lower bug density.

**Key takeaway:** Treat every bug report as a quality opportunity, not just a task. Ask "why did this get through?" for every escaped defect and close the process gap. Write bug reports as if the developer has zero context — precise steps, exact error messages, specific environment details. Track defect cause categories over time: recurring "requirements misunderstood" defects indicate a communication process problem; recurring "null pointer" defects indicate insufficient null handling conventions. Fix the process, not just the defect.` },
    { id: 11, name: "Defect Severity vs Priority", desc: `Severity and priority are two independent dimensions for classifying defects, and conflating them leads to misallocated engineering effort. Severity measures the technical impact of a defect — how badly it breaks the system. Priority measures the business urgency of fixing it — how quickly it must be resolved relative to other work. High severity does not always mean high priority, and high priority does not always mean high severity. Understanding the distinction enables rational defect triage decisions.

**How it works:**
- **Severity levels:** Critical — system crash, data loss, security breach, core functionality completely unusable (user cannot checkout at all). Major — significant functionality impaired, no workaround (payment works for Visa but completely fails for Mastercard). Minor — functionality works but with inconvenience, workaround exists (date picker doesn't work; user can type the date manually). Trivial/Cosmetic — visual issues, typos, minor UI inconsistencies with no functional impact.
- **Priority levels:** P0 — stop everything, fix immediately, may require hotfix to production. P1 — fix in current sprint, block release. P2 — fix in next sprint. P3 — scheduled for a future release. P4 — acknowledged, fix when convenient (or may never be fixed). Priority is a business decision made by product owners, not a technical decision made by developers.
- **The 2×2 matrix — four key quadrants:**
- **High severity, high priority:** Data corruption on checkout — fix immediately.
- **High severity, low priority:** Critical bug in a feature used by 0.01% of users, with a documented workaround — fix, but not necessarily this sprint.
- **Low severity, high priority:** Typo in the company name on the homepage — technically trivial but visible to millions of users and brand-damaging — fix today.
- **Low severity, low priority:** Minor misalignment in a rarely-visited settings page — cosmetic, schedule at convenience.
- **Avoiding severity/priority conflation:** "I'll mark it Critical because I want it fixed fast" is severity inflation — it corrupts the severity metric's value as a technical assessment. Priority is the right lever for urgency. Severity should reflect objective technical impact; priority should reflect business context.
- **Release gates:** Typically: any open Critical or P0 defect blocks release. P1 must be resolved or explicitly accepted by a business owner. P2 and below may be released with known issues documented in release notes.

**Real-world example:** Twitter (now X) experienced a defect in 2022 where the "Edit Tweet" feature (newly released) allowed editing a tweet after it had been retweeted and quote-tweeted by thousands of users — changing what those users had shared without their knowledge. Severity: Major (feature behaves incorrectly, affects user trust). Priority: P0 (the feature had launched to media fanfare and the bug was immediately reported by journalists). The fix required both an immediate hotfix (P0) and an architectural change to how edit history is stored and displayed (higher severity, longer fix timeline). Correct severity and priority assignment drove the appropriate two-track response.

**Key takeaway:** Separate the technical assessment (severity — what broke and how badly) from the business decision (priority — when to fix it). Both fields are necessary; neither substitutes for the other. Establish and document severity definitions for your organisation — different teams have different thresholds for "critical." Review defect priority in sprint planning with product owners, not just in engineering discussions — priority is a product decision with business context that developers often lack.` },
    { id: 12, name: "Test Coverage", desc: `Test coverage is a measure of the degree to which tests exercise a system — what percentage of code paths, requirements, or scenarios have been tested. It is one of the most useful and most misunderstood metrics in software testing. High coverage provides confidence that the test suite exercises the system broadly; it does not guarantee correctness. A test with a weak oracle (no meaningful assertions) can achieve 100% line coverage while testing nothing of value. Coverage is a necessary condition for quality confidence, not a sufficient one.

**How it works:**
- **Code coverage types (structural coverage):**
- **Line/statement coverage:** Percentage of executable lines executed by tests. Simplest metric; lowest bar. Missing a line means there is zero chance a test catches a bug on that line.
- **Branch coverage:** Percentage of code branches (both sides of every if/else, each case of a switch) executed. Stronger than line coverage — a test can execute a line while never testing the else branch. Industry standard for most applications.
- **Function/method coverage:** Percentage of functions called by tests. Useful at a module level; too coarse to guide individual test design.
- **MC/DC (Modified Condition/Decision Coverage):** Each condition in a decision independently affects the outcome — required for aviation (DO-178C), medical devices (IEC 62304), and automotive (ISO 26262) software. The most rigorous structural coverage criterion.
- **Requirement coverage (functional coverage):** What percentage of documented requirements have at least one test case? Different from code coverage — you can have 100% code coverage with 0% requirement coverage if tests are written bottom-up from code rather than top-down from requirements.
- **The 100% coverage fallacy:** "We have 100% coverage" provides false assurance if: (1) tests have weak assertions (they execute the code but don't verify correctness), (2) the requirements themselves are wrong, (3) integration and system interactions are not tested despite full unit coverage, (4) test data is limited to happy paths. 100% coverage with bad tests is worse than 60% coverage with good tests — it creates false confidence.
- **Coverage targets:** Industry benchmarks: 80% line coverage for general applications, 70% branch coverage, 100% for safety-critical paths (payment, authentication, data migration). The right target depends on risk — more coverage for higher-risk code, less for lower-risk. A 40% coverage of the payment module and 95% coverage of a static content module might be the wrong distribution even if the average is 70%.

**Real-world example:** Google's testing culture mandates a minimum readability standard for test coverage in critical systems. Their internal "Test Certified" levels require: Level 1 (unit test coverage measured and visible), Level 2 (80% line coverage or higher), Level 3 (significant integration test coverage), with emergency production changes requiring post-hoc test coverage as a condition of staying deployed. Critically, Google pairs coverage metrics with mutation testing — deliberately introducing small code mutations and checking that tests catch them. This validates that tests are meaningful, not just present.

**Key takeaway:** Measure coverage but don't worship it. Set coverage thresholds per risk tier of the codebase (higher for payment/auth, lower for UI components), enforce them in CI, and fail builds that regress below the threshold. More importantly, review coverage reports to find uncovered branches — these are the specific untested scenarios, not just a number. Complement code coverage with requirement coverage matrices and exploratory testing to catch what structural metrics miss.` },
    { id: 13, name: "Test Environment", desc: `A test environment is the complete configuration — hardware, operating system, software dependencies, network topology, database state, and external service connections — in which tests are executed. The fundamental principle: the closer a test environment is to production, the more trustworthy its test results. An environment that differs significantly from production will pass tests that fail in production and vice versa. Environment parity is not a nice-to-have — it is a prerequisite for meaningful testing.

**How it works:**
- **Environment tiers:** Most organisations maintain multiple environments serving different purposes: Development (local developer machines, highly variable, used for unit tests and local verification), Integration/CI (automated, consistent, used for integration tests on every PR), Staging/Pre-production (mirrors production as closely as possible, used for final validation before release), Production (the real system; monitored continuously via synthetic transactions). Each tier trades off fidelity against speed and cost.
- **Infrastructure as Code (IaC):** Environments should be defined in code (Terraform, Kubernetes manifests, Docker Compose, Ansible) and version-controlled. This ensures environments are reproducible, consistent, and not subject to configuration drift (the gradual divergence of an environment from its intended state due to manual changes). "Works on my machine" bugs are eliminated when all environments derive from the same IaC definition.
- **Environment parity challenges:** Perfect parity is often impossible — production hardware, production data volumes, and production traffic patterns can't be replicated exactly. Key parity points that matter most: database schema and migration state, environment variables and configuration, third-party service versions (if mocked in lower environments, ensure mock fidelity), and network topology (load balancer configuration, TLS termination, firewall rules that differ between environments).
- **Data in test environments:** Production data in test environments creates privacy and compliance risks (GDPR, HIPAA). Anonymised production data snapshots provide realistic data volumes and patterns without exposing PII. Synthetic data generation (Faker libraries, factory patterns) provides controllable, repeatable data without privacy concerns. Test data management — provisioning, resetting, and cleaning test data — is often the most operationally complex part of test environment management.
- **Ephemeral environments:** Preview environments (one per PR or feature branch, spun up automatically, torn down after merge) enable testing in isolated, production-like environments without shared staging environment conflicts. Vercel, Netlify, Railway, and Render all offer preview deployment for every PR. The review app pattern (Heroku's term) has become standard in modern CI/CD.

**Real-world example:** Stripe requires that their staging environment receive mirrored production traffic — a percentage of real payment API calls are replayed (with sanitised payment data) against staging in real time. This guarantees that staging continuously validates against real-world traffic patterns, not just curated test cases. When a staging failure occurs under real traffic patterns, it surfaces environment-specific issues that synthetic test data would miss. This practice — production traffic mirroring to staging — is one of the most effective techniques for ensuring environment parity.

**Key takeaway:** Define all environments in code (IaC), version-control them, and automate provisioning. Achieve staging-to-production parity on the dimensions that matter most: database schema, configuration, and network topology. Use anonymised production data snapshots in staging rather than synthetic data alone — real data shapes and distributions expose bugs that idealised test data misses. Adopt ephemeral preview environments for PR-level testing — they eliminate "works in staging but fails in production because someone changed staging manually" issues.` },
    { id: 14, name: "Test Data Management", desc: `Test data management (TDM) is the discipline of creating, maintaining, provisioning, and cleaning up the data needed to execute tests. Tests are only as good as the data they run against — a test using unrealistic data may pass while the same scenario with production data volumes or edge-case values fails. TDM is operationally one of the hardest problems in test engineering: data grows, becomes stale, contains PII, creates coupling between test runs, and is often the primary cause of flaky tests and inconsistent test results.

**How it works:**
- **Data generation approaches:**
- **Static fixtures:** Hard-coded test data in JSON, YAML, or SQL files committed to the repository. Simple, reproducible, but brittle — a schema change requires updating every fixture. Best for: lookup tables, configuration data, small datasets with known structure.
- **Factory pattern:** Programmatically generate objects with sensible defaults, overridable per test. In Python: factory-boy. In Ruby: FactoryBot. In JavaScript: fishery or custom builders. user = UserFactory.create(email: "test@example.com", role: :admin). Each test creates exactly the data it needs; no shared state between tests.
- **Seed scripts:** Database initialisation scripts that populate a baseline state (product catalogue, pricing tiers, admin accounts). Run at environment startup, not per test. Provides consistent baseline without recreating it for every test run.
- **Anonymised production cloning:** Copy production data with PII fields replaced (email → generated@fake.com, name → "Test User", card number → fake card number). Provides realistic data volumes, distributions, and edge cases. Requires a robust anonymisation pipeline and regular refresh to stay current.
- **Test isolation:** Each test should start with a known data state and not depend on data created by other tests. Strategies: transaction rollback (wrap each test in a transaction, roll back after — database returns to clean state), database truncation and re-seeding (slow but thorough), or factory-based setup with unique identifiers per test (email = f"test+{uuid}@example.com").
- **PII and compliance:** GDPR, HIPAA, and PCI-DSS restrict using real personal, health, or payment data in non-production environments. Anonymisation is mandatory for compliant TDM. Tokenisation replaces sensitive values with realistic but fake equivalents that preserve format (a credit card number replaced with a validly formatted fake number passes format validation in tests).

**Real-world example:** Airbnb's test data management for their booking system uses a "data builder" pattern: each test constructs the precise data state it needs using builders (ListingBuilder.create().with_host(admin_host).with_price(100).with_availability([tomorrow]).build()). The builders handle all the relational complexity (creating the host user, the listing, the availability calendar, the pricing rules) with one line per test. No shared fixtures, no test order dependencies. This approach was adopted after years of brittle fixture-based tests that broke whenever the schema changed.

**Key takeaway:** Adopt the factory/builder pattern for test data generation — it produces isolated, reproducible, maintainable tests. Never share mutable test data between tests — it creates hidden dependencies that cause tests to pass in isolation but fail when run in a suite. Implement database cleanup between tests (transaction rollback is fastest). Treat PII in test data as a compliance violation, not a convenience — implement anonymisation pipelines and never use real customer data in lower environments.` },
    { id: 15, name: "Test Harness", desc: `A test harness is the collection of software and test data configured to test a program unit — providing the environment, scaffolding, and tooling necessary to execute tests automatically and collect results. It is the infrastructure layer that sits between the test runner and the system under test. A test harness handles: calling the code under test, providing inputs, capturing outputs, comparing against expected results, and reporting pass/fail status. Without a harness, tests are manual procedures; with a harness, they are automated specifications.

**How it works:**
- **Components of a test harness:**
- **Test runner:** Discovers and executes test suites and cases. Reports results. Examples: pytest (Python), JUnit (Java), Jest (JavaScript), Go's testing package. The runner provides the main() function that runs all tests when invoked.
- **Test stubs:** Simplified implementations of components the code under test depends on — simulating a dependency's behaviour for the purpose of the test. A stub for a payment gateway always returns "payment approved" for any input. Stubs are pre-programmed with canned responses.
- **Test drivers:** Code that calls the component under test from outside — the "caller" that exercises the module when no real caller is available (for unit testing a library function, for example). In most application testing, the test framework itself serves as the driver.
- **Mocks and spies:** Mocks verify interactions (was this function called with these arguments?). Spies observe calls without replacing behaviour (how many times was this function called?). The mock library (unittest.mock, Jest's jest.fn(), Mockito for Java) is a core test harness component.
- **Assertion library:** The mechanism for verifying expected outcomes. assert result == expected (Python), expect(result).toBe(expected) (Jest), assertThat(result, is(expected)) (JUnit + Hamcrest). Fluent assertion libraries (AssertJ, Chai, Hamcrest) produce more readable failure messages.
- **Integration test harness:** For integration tests, the harness includes: in-memory or containerised dependencies (TestContainers for Docker-based real databases/message brokers in tests), HTTP request interceptors (WireMock, Nock) for mocking external API calls, and database fixtures for test data state.
- **CI integration:** The harness must integrate with CI to enable automated execution on every commit: exit codes (0 = pass, non-zero = fail), machine-readable output (JUnit XML report format, consumed by CI dashboards), parallel test execution configuration, and coverage report generation.

**Real-world example:** Django's test framework is a complete test harness: it provides a test runner (python manage.py test), an isolated in-memory SQLite database per test run (no production data contamination), a test client that simulates HTTP requests without a running server, a RequestFactory for unit testing views, fixtures for database state setup, and override_settings for testing configuration variations. This complete harness is why Django applications are consistently well-tested — the framework removes every friction point from writing and running tests.

**Key takeaway:** Invest in your test harness infrastructure early — it pays compound interest. A test suite that is slow to run, painful to set up, or produces inconsistent results will be abandoned. Key investments: fast test execution (parallelisation, in-memory databases, avoiding real network calls), reliable reset between tests (no flakiness from shared state), and readable test output that identifies exactly what failed and why. The best harness is one that makes writing a new test the path of least resistance.` },
    { id: 16, name: "Entry & Exit Criteria", desc: `Entry and exit criteria are the formal conditions that define when a testing phase can begin and when it is complete. Without them, testing starts too early (on incomplete builds), runs too long (endless bug-fixing without a clear stopping point), or ends too soon (before sufficient coverage is achieved). Entry and exit criteria transform the subjective question "are we done testing?" into an objective, answerable question based on pre-defined measurements.

**How it works:**
- **Entry criteria — conditions before testing begins:**
- Build criteria: code is feature-complete, merged, and successfully built. No failing unit tests in the build.
- Environment criteria: test environment is provisioned, accessible, and seeded with required test data.
- Documentation criteria: requirements or user stories are complete and approved; test cases are written and reviewed.
- Smoke test criteria: the build passes a predefined smoke test suite verifying basic functionality (the application launches, login works, main navigation functions). A build that fails smoke tests is not ready for systematic testing.
- Predecessor criteria: all blocking defects from the previous test cycle are resolved.
- **Exit criteria — conditions to stop testing and approve release:**
- Coverage criteria: code coverage target met (e.g., 80% branch coverage), requirement coverage complete (all P0/P1 requirements have passing tests).
- Defect criteria: zero open Critical (or P0) defects, all P1 defects resolved or explicitly deferred with stakeholder approval, P2/P3 defects logged and triaged.
- Test execution criteria: all planned test cases executed (or explicitly descoped with justification).
- Sign-off: defined stakeholders (QA lead, product owner, engineering lead) have reviewed results and approved release.
- **Why entry criteria matter:** Starting testing on an incomplete build wastes QA time on defects that would be caught by the developer's own tests. Establishing entry criteria prevents this — testing begins on a foundation that is stable enough to be tested systematically.
- **Why exit criteria matter:** Without exit criteria, testing continues indefinitely (there is always one more bug to find) or is cut arbitrarily by schedule pressure with no documented risk basis. Exit criteria make the stopping decision objective and auditable — a release is approved because it met the criteria, not because time ran out.

**Real-world example:** Atlassian's release process for Jira Cloud defines formal entry and exit criteria per release candidate. Entry: feature freeze complete, smoke suite passes at > 99%, all P0/P1 bugs from the previous release resolved. Exit: 100% of release-blocking tests pass, zero P0 open defects, P1 defects resolved or have explicit VP of Engineering sign-off for deferral, Core Web Vitals regression check passes, security scan shows no new high-severity findings. This explicit criteria list means the release decision is made against a documented standard, not personal opinion about readiness.

**Key takeaway:** Define entry and exit criteria before the test cycle begins — not during it. Entry criteria should be objectively verifiable (either the smoke suite passes or it doesn't). Exit criteria should be measurable (coverage percentage, defect counts by severity) and include explicit human sign-off from defined stakeholders. When exit criteria aren't met, the decision to release anyway is an explicit risk acceptance — document it, get the right approvals, and make it visible. Undocumented "we decided to release anyway" decisions are how escaped defects happen.` },
    { id: 17, name: "Traceability Matrix", desc: `A Requirements Traceability Matrix (RTM) is a document (or structured data) that maps each requirement to the test case(s) that verify it, and each test case back to the requirement it covers. It ensures bidirectional traceability: you can ask "which tests cover requirement R?" (forward traceability) and "which requirement does test T cover?" (backward traceability). The RTM is the primary tool for verifying test coverage at the requirements level — a complement to code coverage metrics that measures structural coverage rather than requirement coverage.

**How it works:**
- **Structure:** Columns: Requirement ID | Requirement Description | Test Case IDs | Test Status | Coverage Status. Each row is one requirement; test case IDs in each row are the tests that cover it. Status shows whether the requirement's tests have been executed and passed.
- **Forward traceability (Requirements → Tests):** Ensures every requirement has at least one test. Empty rows (requirements with no test cases) represent coverage gaps — features that could be shipped broken without any test catching it. Forward traceability is the coverage question: "have we tested everything we're supposed to?"
- **Backward traceability (Tests → Requirements):** Ensures every test case traces to a requirement. Test cases without a requirement link are either testing undocumented behaviour (which may indicate scope creep or missing documentation) or are orphaned tests that should be removed. Backward traceability is the validity question: "is every test we're running actually necessary?"
- **When requirements change:** A change to requirement R immediately shows all test cases linked to R — they must be reviewed and potentially updated. Without an RTM, requirement changes frequently result in stale test cases that no longer match the updated behaviour, silently reducing coverage quality.
- **Scope of use:** RTMs are most valuable in: regulated industries (FDA, FAA, ISO certification) where auditability of requirement coverage is mandatory, large projects where the team cannot maintain informal coverage tracking, and any project with formal acceptance criteria that must be demonstrated to stakeholders.
- **Lightweight alternatives for agile teams:** Full RTM maintenance is high-overhead for fast-moving agile teams. Lightweight versions: link test cases to user stories in the project management tool (Jira, Linear, GitHub Issues), use BDD scenarios (each scenario is a testable requirement — the scenario IS the RTM entry), or maintain a coverage matrix per epic/feature rather than per story.

**Real-world example:** Medical device software companies (Medtronic, Philips Healthcare) are required by FDA regulations (21 CFR Part 820) to maintain RTMs demonstrating that all device requirements are covered by verified tests before release. The RTM is part of the Device History Record — audited by the FDA during inspections. A gap in the RTM (requirement without a passing test) is a regulatory non-compliance that can prevent device approval. This regulatory pressure has made RTMs non-negotiable in medical device software, even when their maintenance is operationally expensive.

**Key takeaway:** For regulated industries or large formal projects, maintain a full RTM — the auditability it provides is worth the overhead. For agile teams, use lightweight traceability: link tests to stories in your project management tool and track coverage per feature rather than per line item. The core value — ensuring every requirement is tested and every test is traceable — can be achieved with varying formality. The danger is zero traceability: shipping without any way to answer "which requirements have been tested and passed?"` },
  ],
};
export default fundamentals;
